-- Migration 039: Fen Bilimleri sinif 5-8 tam re-seed
-- Mevcut kısa kodlu (FB.x.y.z) kayıtları sil, doğru 5-parçalı kodlarla (FB.x.y.z.w) ekle
-- PDF: refs/mufredat-2025/2025825154137627-fen bilimleri.pdf
-- Toplam: 28+36+36+43 = 143 yeni kayıt

DO $$
DECLARE
  fb_id UUID;
BEGIN
  SELECT id INTO fb_id FROM branslar WHERE slug = 'fen_bilimleri';

  -- Mevcut sinif 5-8 kayıtlarını sil (kod format yanlıştı: FB.x.y.z)
  DELETE FROM kazanimlar WHERE brans_id = fb_id AND sinif IN (5, 6, 7, 8);

  -- Yeni kayıtları ekle (doğru 5-parçalı kod formatı: FB.x.y.z.w)
  INSERT INTO kazanimlar (brans_id, kod, sinif, unite_no, unite_ad, ad, aciklama, ders, okul_tipi, ders_turu) VALUES
  (fb_id, 'FB.5.1.1.1', 5, 1, 'GÖKYÜZÜNDEKİ KOMŞULARIMIZ VE BİZ', 'Güneş''in yapısı ve dönme hareketi ile ilgili bilgileri toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.1.2.1', 5, 1, 'GÖKYÜZÜNDEKİ KOMŞULARIMIZ VE BİZ', 'Ay''ın özellikleri, dönme ve dolanma hareketleri ile ilgili bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.1.2.2', 5, 1, 'GÖKYÜZÜNDEKİ KOMŞULARIMIZ VE BİZ', 'Ay''ın evrelerini temsil eden bilimsel model oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.1.3.1', 5, 1, 'GÖKYÜZÜNDEKİ KOMŞULARIMIZ VE BİZ', 'Güneş, Dünya ve Ay''ın birbirlerine göre hareketlerini ve hacimsel büyüklüklerini temsil eden bilimsel model oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.2.1.1', 5, 2, 'KUVVETİ TANIYALIM', 'Kuvveti büyüklüğü ile tanımlayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.2.1.2', 5, 2, 'KUVVETİ TANIYALIM', 'Basit araç gereçler kullanarak bir dinamometre modeli tasarlayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.2.2.1', 5, 2, 'KUVVETİ TANIYALIM', 'Kütleye etki eden yer çekimi kuvvetini ağırlık olarak tanımlayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.2.3.1', 5, 2, 'KUVVETİ TANIYALIM', 'Sürtünme kuvvetinin çeşitli ortamlardaki etkilerine yönelik tümevarımsal akıl yürütebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.2.3.2', 5, 2, 'KUVVETİ TANIYALIM', 'Günlük yaşamda sürtünmeyi artırma veya azaltmaya yönelik bilimsel bir model tasarlayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.3.1.1', 5, 3, 'CANLILARIN YAPISINA YOLCULUK', 'Bitki ve hayvan hücrelerini temel kısımları ve özellikleri açısından karşılaştırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.3.1.2', 5, 3, 'CANLILARIN YAPISINA YOLCULUK', 'Hücre-doku-organ-sistem-organizma kavramlarını yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.3.2.1', 5, 3, 'CANLILARIN YAPISINA YOLCULUK', 'Destek ve hareket sistemine ait yapıları sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.3.2.2', 5, 3, 'CANLILARIN YAPISINA YOLCULUK', 'Destek ve hareket sisteminin sağlığı için yapılması gerekenler konusunda bilgi toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.4.1.1', 5, 4, 'IŞIĞIN DÜNYASI', 'Bir kaynaktan çıkan ışığın her yönde doğrusal bir yol izlediğini gözlem yoluyla açıklayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.4.2.1', 5, 4, 'IŞIĞIN DÜNYASI', 'Maddeleri ışığı geçirme durumlarına göre sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.4.3.1', 5, 4, 'IŞIĞIN DÜNYASI', 'Tam gölgeye yönelik bilimsel gözlem yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.5.1.1', 5, 5, 'MADDENİN DOĞASI', 'Maddeleri tanecikli, boşluklu ve hareketli yapısına göre sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.5.2.1', 5, 5, 'MADDENİN DOĞASI', 'Isı ve sıcaklık kavramlarını karşılaştırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.5.2.2', 5, 5, 'MADDENİN DOĞASI', 'Sıcaklığı farklı olan sıvıların karıştırılması sonucu ısı alışverişi olduğuna yönelik bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.5.3.1', 5, 5, 'MADDENİN DOĞASI', 'Maddenin ısı etkisiyle hâl değiştirebileceğini bilimsel gözleme dayalı tahmin edebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.5.4.1', 5, 5, 'MADDENİN DOĞASI', 'Maddeleri ısı iletimi bakımından sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.5.4.2', 5, 5, 'MADDENİN DOĞASI', 'Isı yalıtımını gösteren model oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.6.1.1', 5, 6, 'YAŞAMIMIZDAKİ ELEKTRİK', 'Bir elektrik devresindeki elemanları sembollerinin olup olmamasına göre sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.6.1.2', 5, 6, 'YAŞAMIMIZDAKİ ELEKTRİK', 'Şemasını çizdiği elektrik devresine uygun deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.6.2.1', 5, 6, 'YAŞAMIMIZDAKİ ELEKTRİK', 'Bir elektrik devresindeki ampul parlaklığını etkileyen değişkenlerin neler olduğuna ilişkin hipotez oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.7.1.1', 5, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE GERİ DÖNÜŞÜM', 'Evsel atıklarda geri dönüştürülebilen ve dönüştürülemeyen maddeleri sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.7.1.2', 5, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE GERİ DÖNÜŞÜM', 'Kaynakların etkili kullanımı konusunda geri dönüşümün önemli olduğuna yönelik bilimsel çıkarımda bulunabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.5.7.1.3', 5, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE GERİ DÖNÜŞÜM', 'Yakın çevresinde atık yönetiminin uygulanabilirliğine ilişkin deneyimlerini yansıtabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.1.1.1', 6, 1, 'GÜNEŞ SİSTEMİ VE TUTULMALAR', 'Güneş sistemindeki gezegenleri niteliklerine göre sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.1.1.2', 6, 1, 'GÜNEŞ SİSTEMİ VE TUTULMALAR', 'Güneş sistemi ile ilgili bilimsel model oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.1.2.1', 6, 1, 'GÜNEŞ SİSTEMİ VE TUTULMALAR', 'Güneş ve Ay tutulması ile ilgili bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.1.2.2', 6, 1, 'GÜNEŞ SİSTEMİ VE TUTULMALAR', 'Güneş ve Ay tutulması ile ilgili bilimsel model oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.2.1.1', 6, 2, 'KUVVETİN ETKİSİNDE HAREKET', 'Bir cisme etki eden aynı doğrultudaki kuvvetler arasındaki ilişkileri açıklayarak bileşke kuvveti yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.2.1.2', 6, 2, 'KUVVETİN ETKİSİNDE HAREKET', 'Dengelenmiş ve dengelenmemiş kuvvetlerin etkisi altındaki bir cismin hareketine yönelik deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.2.2.1', 6, 2, 'KUVVETİN ETKİSİNDE HAREKET', 'Sürat ve hız kavramlarını karşılaştırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.3.1.1', 6, 3, 'CANLILARDA SİSTEMLER', 'Eşeyli ve eşeysiz üremeyi karşılaştırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.3.1.2', 6, 3, 'CANLILARDA SİSTEMLER', 'Bitkilerde üreme, büyüme ve gelişme hakkında bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.3.1.3', 6, 3, 'CANLILARDA SİSTEMLER', 'Tohumun çimlenmesine etki eden faktörlere ilişkin hipotez oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.3.1.4', 6, 3, 'CANLILARDA SİSTEMLER', 'Hayvanlarda üreme, büyüme ve gelişme hakkında bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.3.1.5', 6, 3, 'CANLILARDA SİSTEMLER', 'İnsanda üremeyi sağlayan yapı ve organlar arasındaki ilişkileri çözümleyebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.3.2.1', 6, 3, 'CANLILARDA SİSTEMLER', 'Sinir sisteminin görevlerini model üzerinde gözlemleyebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.3.2.2', 6, 3, 'CANLILARDA SİSTEMLER', 'İç salgı bezlerinin vücut için önemini yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.3.2.3', 6, 3, 'CANLILARDA SİSTEMLER', 'Çocukluktan ergenliğe geçişte oluşan bedensel ve ruhsal değişimleri genelleyebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.3.2.4', 6, 3, 'CANLILARDA SİSTEMLER', 'Denetleyici ve düzenleyici sistemlerin sağlığı için yapılması gerekenlerle ilgili bilgi toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.4.1.1', 6, 4, 'IŞIĞIN YANSIMASI VE RENKLER', 'Işığın farklı yüzeylerdeki yansıma olaylarına ilişkin bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.4.1.2', 6, 4, 'IŞIĞIN YANSIMASI VE RENKLER', 'Işığın yansımasında gelen ışın, yansıyan ışın ve yüzeyin normali arasındaki ilişkiyi kanıt kullanarak açıklayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.4.2.1', 6, 4, 'IŞIĞIN YANSIMASI VE RENKLER', 'Günlük hayattaki ayna çeşitlerine ilişkin bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.4.3.1', 6, 4, 'IŞIĞIN YANSIMASI VE RENKLER', 'Işığın madde ile etkileşimi sonucunda soğurulabileceğini gözlemleyebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.4.3.2', 6, 4, 'IŞIĞIN YANSIMASI VE RENKLER', 'Beyaz ışığın tüm ışık renklerinin bileşiminden oluştuğuna ilişkin bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.4.3.3', 6, 4, 'IŞIĞIN YANSIMASI VE RENKLER', '“Bazı zamanlarda satın aldığınız giysinin renginin evde mağazadakinden farklı olduğunu görebilirsiniz. Sizce bu durumun nedeni nedir?” vb sorular ile tartışma sağlanır (E1.1, SDB2.1, KB2.18). Sınıfa getirilen beyaz renkli bir cisim Güneş ışığı ve kırmızı ışık altında', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.4.3.4', 6, 4, 'IŞIĞIN YANSIMASI VE RENKLER', 'Güneş enerjisinin günlük hayat ve teknolojideki yenilikçi uygulamalarına ilişkin eleştirel düşünebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.5.1.1', 6, 5, 'MADDENİN AYIRT EDİCİ ÖZELLİKLERİ', 'Isı etkisiyle maddelerin genleşip büzüleceğine yönelik bilimsel gözleme dayalı tahmin edebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.5.2.1', 6, 5, 'MADDENİN AYIRT EDİCİ ÖZELLİKLERİ', 'Maddelerin erime, donma ve kaynama noktasını gösteren deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.5.3.1', 6, 5, 'MADDENİN AYIRT EDİCİ ÖZELLİKLERİ', 'Yoğunluğa ilişkin hesaplamalar yaparak bilimsel veriye dayalı tahmin edebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.5.3.2', 6, 5, 'MADDENİN AYIRT EDİCİ ÖZELLİKLERİ', 'Deneyler sonucunda çeşitli maddelerin yoğunluklarına ilişkin tümdengelimsel akıl yürütebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.5.3.3', 6, 5, 'MADDENİN AYIRT EDİCİ ÖZELLİKLERİ', 'Suyun katı ve sıvı hâllerine ait yoğunlukları karşılaştırarak bu durumun canlılar için önemi hakkında bilimsel çıkarımlar yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.5.3.4', 6, 5, 'MADDENİN AYIRT EDİCİ ÖZELLİKLERİ', 'Yoğunluk ile ilgili bilimsel model oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.6.1.1', 6, 6, 'ELEKTRİĞİN İLETİMİ VE DİRENÇ', 'Maddelerin elektriği iletme durumlarını gösteren deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.6.2.1', 6, 6, 'ELEKTRİĞİN İLETİMİ VE DİRENÇ', 'Elektrik devresindeki ampulün parlaklığının bağlı olduğu değişkenleri belirlemeye yönelik deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.6.2.2', 6, 6, 'ELEKTRİĞİN İLETİMİ VE DİRENÇ', 'Ayarlanabilir direncin ampulün parlaklığına etkilerine yönelik bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.7.1.1', 6, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE ETKİLEŞİM', 'Biyoçeşitliliğin doğal yaşam için önemini sorgulayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.7.1.2', 6, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE ETKİLEŞİM', 'Biyoçeşitliliği tehdit eden faktörleri araştırma verilerine dayalı tahmin edebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.7.2.1', 6, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE ETKİLEŞİM', 'Isınma amaçlı yakıt kullanımının insan ve çevre üzerine etkilerini tartışabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.6.7.2.2', 6, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE ETKİLEŞİM', 'Yakın çevresindeki veya ülkemizdeki bir çevre problemine ilişkin çözüm üretebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.1.1.1', 7, 1, 'UZAY ÇAĞI', 'Uzay araştırmaları için geliştirilen teknolojileri karşılaştırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.1.1.2', 7, 1, 'UZAY ÇAĞI', 'Uzay gözlem araçları ile ilgili bilimsel model oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.1.1.3', 7, 1, 'UZAY ÇAĞI', 'Uzay araştırmalarının yol açabileceği problemleri çözebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.1.2.1', 7, 1, 'UZAY ÇAĞI', 'Yıldızların yaşamını açıklayarak yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.1.2.2', 7, 1, 'UZAY ÇAĞI', 'Yıldız, galaksi ve evren kavramlarını açıklayarak yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.2.1.1', 7, 2, 'KUVVET VE ENERJİYİ KEŞFEDELİM', 'Kuvvetin cisimler üzerindeki etkisine yönelik açık uçlu sorular yöneltilerek beyin fırtına sı tekniği ile öğrencilerin fikirleri alınır (E3.5). Bu fikirlerden yola çıkarak fiziksel anlamda yapılan işin niteliklerini tanımlamaları sağlanır. Öğrencilere günlük yaşamdan görsel ör', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.2.1.2', 7, 2, 'KUVVET VE ENERJİYİ KEŞFEDELİM', 'Enerji çeşitlerinden kinetik ve potansiyel enerjiyi karşılaştırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.2.2.1', 7, 2, 'KUVVET VE ENERJİYİ KEŞFEDELİM', 'Öğrencilerden kinetik ve potansiyel enerjinin birbirine dönüşmesine ilişkin günlük yaşamından örnekler vermeleri istenebilir. Sınıf veya laboratuvar ortamında basit araç gereçler kullanarak sarkaç, serbest düşmeye bırakılan cisim, sarmal yaylar,', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.3.1.1', 7, 3, 'VÜCUDUMUZDAKİ SİSTEMLER', 'Sindirim sistemini oluşturan yapı ve organların görevlerini model üzerinde gözlemleyebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.3.1.2', 7, 3, 'VÜCUDUMUZDAKİ SİSTEMLER', 'Sindirim sisteminin sağlığı için yapılması gerekenler konusunda bilgi toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.3.2.1', 7, 3, 'VÜCUDUMUZDAKİ SİSTEMLER', 'Dolaşım sistemini oluşturan yapı ve organların görevlerini model üzerinde gözlemleyebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.3.2.2', 7, 3, 'VÜCUDUMUZDAKİ SİSTEMLER', 'Kan bağışının toplumsal dayanışma açısından önemini tartışabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.3.2.3', 7, 3, 'VÜCUDUMUZDAKİ SİSTEMLER', 'Dolaşım sisteminin sağlığı için yapılması gerekenler konusunda bilgi toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.3.3.1', 7, 3, 'VÜCUDUMUZDAKİ SİSTEMLER', 'Solunum sistemini oluşturan yapı ve organların görevlerini model üzerinde gözlemleyebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.3.3.2', 7, 3, 'VÜCUDUMUZDAKİ SİSTEMLER', 'Solunum sisteminin sağlığı için yapılması gerekenler konusunda bilgi toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.3.4.1', 7, 3, 'VÜCUDUMUZDAKİ SİSTEMLER', 'Boşaltım sistemini oluşturan yapı ve organları model üzerinde gözlemleyebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.3.4.2', 7, 3, 'VÜCUDUMUZDAKİ SİSTEMLER', 'Boşaltım sisteminin sağlığı için yapılması gerekenler konusunda bilgi toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.4.1.1', 7, 4, 'IŞIĞIN KIRILMASI VE MERCEKLER', 'Ortam değiştiren ışığın izlediği yolu gözlemleyerek kırılma olayına yönelik bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.4.2.1', 7, 4, 'IŞIĞIN KIRILMASI VE MERCEKLER', 'Mercek çeşitlerine yönelik bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.4.2.2', 7, 4, 'IŞIĞIN KIRILMASI VE MERCEKLER', 'Merceklerin günlük hayatta kullanım alanlarını örneklerle sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.1.1', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Öğrencilere maddenin tanecikli yapıdan oluştuğu hatırlatılır. Öğrencilerden parkta oynadıkları sırada bir avuç kum alarak kumu diğer avucuna dökmeleri hayal ettirilebilir. Kum dökerken kum tanelerini fark etmeleri istenebilir. Park zemininin bu kum tanelerinin', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.1.2', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Atom kavramı ile ilgili bilginin ilk olarak ne zaman ortaya çıktığı ve Democritus''tan günümüze nasıl geliştiği öğrencilere belgeseller izletilerek merak uyandırılır. (E1.1). Öğrencilerin atom ile ilgili 5N1K tekniğine göre sorular sormaları istenir (E3.8, SDB2.1). Bu sorular tahtaya', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.1.3', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Maddelerin tanecikli yapısının molekül şeklinde de olabileceği, aynı veya farklı atomların belirli oranlarda bir araya gelerek molekülü oluşturabileceği belirtilir. Atomları modellemede oyun hamuru, pinpon topu vb. malzemeler kullanılarak (E2.5) öğrencilerin', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.1.4', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Öğrencilere elektronların katmanlara dizilimi ile ilgili açık uçlu sorular sorulur. Dublet ve oktet kuralı orbital şemalarına girilmeden verilir. Öğrencilerin atomlarda elektronların dizilimindeki mantıksal ilişkileri ortaya koymaları beklenir. Periyodik tabloda yer alan ilk 18', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.2.1', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Tahtaya saf maddeleri temsil edebilecek çeşitli tanecikli yapı örnekleri çizilerek öğrencilerden bu örnekleri dikkatli bir şekilde incelemeleri istenir (OB4). Öğrencilerden saf maddelerin aynı veya farklı cins atomlardan meydana geldiğini fark etmeleri beklenir.', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.2.2', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Periyodik tablodaki ilk 18 elementin isimlerini sembolleriyle ifade edebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.2.3', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Öğrencilere kitaplarını raflara yerleştirirken belirli ölçütleri dikkate alıp almadıkları ve düzen açısından belirli ölçütlerin olmasının nasıl bir fayda sağlayacağı sorulabilir (SDB2.1, E3.10). Öğrencilerin düşüncelerini özgürce ve kendine güvenerek ifade etmeleri ve', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.2.4', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Öğrencilere farklı cins elementlerin bir araya gelerek bileşikleri oluşturabildiği hatırlatılır. Elementlerin sembollerle gösterilmesinden yola çıkılarak bileşiklerin nasıl gösterilebileceğine dair sorular yöneltilir (SDB2.1, SDB3.1, E3.4). Bileşiklerin de elementler', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.3.1', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Öğrencilerin karışım kavramı ile ilgili ön öğrenmelerini açığa çıkarmak için açık uçlu sorular sorulabilir (SDB2.1, E1.1). Saf maddelerin özellikleri hatırlatılarak saf olmayan maddelerin özelliklerini nitelemeleri istenir (SDB3.1). Bileşiklerle karışımların birbirinden', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.3.2', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Çözünme hızına etki eden faktörler ile ilgili hipotez oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.5.4.1', 7, 5, 'MADDENİN DOĞASINA YOLCULUK', 'Öğrencilere günlük hayattan örnekler verilerek karışımların ayrılıp ayrılamayacağı ile ilgili açık uçlu sorular yöneltilebilir. Karışımları ayırmak için hangi fiziksel yöntemlerin kullanılabileceği ile ilgili beyin fırtınası tekniği yaptırılabilir (E3.4, SDB2.1). Karışımları', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.6.1.1', 7, 6, 'ELEKTRİKLENME', 'Elektriklenme ile ilgili bilgi toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.6.1.2', 7, 6, 'ELEKTRİKLENME', 'Elektriklenme çeşitlerini belirlemeye yönelik deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.6.1.3', 7, 6, 'ELEKTRİKLENME', 'Cisimlerin elektrik yüklerini sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.7.1.1', 7, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE ENERJİ', 'Besin zincirindeki canlıları arasındaki ilişkileri yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.7.7.2.1', 7, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE ENERJİ', 'Kaynakların tasarruflu kullanımının önemini sorgulayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.1.1.1', 8, 1, 'GÖKYÜZÜNDEKİ', 'Dünya''nın Güneş etrafındaki hareketi ve eksen eğikliğinin sonuçları ile ilgili bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.1.2.1', 8, 1, 'GÖKYÜZÜNDEKİ', 'İklim ve hava olaylarını karşılaştırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.2.1.1', 8, 2, 'YAŞAMI KOLAYLAŞTIRAN KUVVET', 'Basit makineleri sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.2.1.2', 8, 2, 'YAŞAMI KOLAYLAŞTIRAN KUVVET', 'Günlük yaşamda iş kolaylığı sağlayacak bilimsel model oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.3.1.1', 8, 3, 'YAŞAMIN GİZEMİ', 'Nükleotid, gen, DNA ve kromozom kavramları arasındaki ilişkiyi yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.3.1.2', 8, 3, 'YAŞAMIN GİZEMİ', 'DNA''nın yapısını model üzerinde gözlemleyebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.3.2.1', 8, 3, 'YAŞAMIN GİZEMİ', 'Mitoz ve mayoz kavramları arasındaki ilişkiyi karşılaştırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.3.3.1', 8, 3, 'YAŞAMIN GİZEMİ', 'Kalıtımla ilgili kavramları yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.3.3.2', 8, 3, 'YAŞAMIN GİZEMİ', 'Tek karakter çaprazlamaları ile ilgili problemler çözerek sonuçları değerlendirebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.3.3.3', 8, 3, 'YAŞAMIN GİZEMİ', 'Akraba evliliklerinin genetik sonuçlarını tartışabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.3.4.1', 8, 3, 'YAŞAMIN GİZEMİ', 'Mutasyonla ilgili bilgi toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.3.4.2', 8, 3, 'YAŞAMIN GİZEMİ', 'Canlıların yaşadıkları çevreye uyumlarına ilişkin bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.4.1.1', 8, 4, 'SESİN DÜNYASI', 'Öğrencilerin istedikleri bir müzik aletini sınıf ortamına getirmeleri istenebilir. Çeşitli mü zik aletlerini (saz, davul, flüt vb.) kullanarak sesin oluşumuna yönelik gözlem yapmaları sağlanır (SDB1.2, E2.5). Sınıf veya laboratuvar ortamında olabildiğince sessiz bir ortam', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.4.1.2', 8, 4, 'SESİN DÜNYASI', 'Sesin yayılabildiği ortamlara yönelik deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.4.1.3', 8, 4, 'SESİN DÜNYASI', 'Sesin frekansına göre ince veya kalın olarak işitilmesine neden olan ses özellikleri ile ilgili deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.4.2.1', 8, 4, 'SESİN DÜNYASI', 'Ders öncesinde, ses kaynağından uzaklığın ve ses şiddetinin işitmeye etkisi ile ilgili bir se naryo veya problem durumu öğretmen tarafından hazırlanır. Öğrencilerden bu senaryoda verilen problemi tanımlamaları istenir (SDB3.3). Tanımladıkları problemde ses kaynağın', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.4.2.2', 8, 4, 'SESİN DÜNYASI', 'Farklı maddeler ile etkileşimi sonucunda sesin iletilmesi, yansıması ve soğurulmasına ilişkin bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.4.2.3', 8, 4, 'SESİN DÜNYASI', 'Ses kirliliğini önlemeye yönelik bilimsel sorgulama yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.5.1.1', 8, 5, 'PERİYODİK TABLO VE MADDENİN ETKİLEŞİMİ', 'Elementleri periyodik tablo üzerinde metal, ametal, yarımetal ve soy gaz olarak sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.5.2.1', 8, 5, 'PERİYODİK TABLO VE MADDENİN ETKİLEŞİMİ', 'Fiziksel ve kimyasal değişimler ile ilgili bilimsel gözleme dayalı tahmin edebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.5.3.1', 8, 5, 'PERİYODİK TABLO VE MADDENİN ETKİLEŞİMİ', 'Kimyasal tepkimelerle ilgili bilimsel çıkarım yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.5.3.2', 8, 5, 'PERİYODİK TABLO VE MADDENİN ETKİLEŞİMİ', 'Kimyasal tepkimelerin günlük yaşamdaki etkilerine yönelik bilgi toplayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.5.4.1', 8, 5, 'PERİYODİK TABLO VE MADDENİN ETKİLEŞİMİ', 'Asit ve bazlar konusu ile ilgili kavram yanılgıları iki aşamalı teşhis testleri gibi teknikler kullanılarak belirlenebilir. Öğrencilere iyon konusu ile ilgili açık uçlu sorular sorularak asit ve bazların sulu çözeltilerine verdikleri iyonlar belirtilir. Asit ve bazların temizlik', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.5.4.2', 8, 5, 'PERİYODİK TABLO VE MADDENİN ETKİLEŞİMİ', 'Sınıfa saf su, sabun, limon suyu, sirke, deterjan, şampuan, yoğurt, süt, çamaşır suyu vb. malzemeler getirilir. Öğrenciler gruplara ayrılarak gerekli uyarılar yapılır ve öğrencilerin güvenlik önlemleri almaları sağlanır (D3.4, SDB2.2). Her gruptan aynı malzemelerden', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.5.4.3', 8, 5, 'PERİYODİK TABLO VE MADDENİN ETKİLEŞİMİ', 'Öğrencilere günlük yaşamda karşılaşılan asitlik değeri farklı malzemelerden örnekler verilerek gösterdikleri asitlik-bazlık derecesinin birbirinden farklı olabileceğine yönelik açık uçlu sorular sorulabilir. pH cetveli ile maddelerin asitlik-bazlık derecesinin', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.5.4.4', 8, 5, 'PERİYODİK TABLO VE MADDENİN ETKİLEŞİMİ', 'Asit ve bazların çeşitli maddeler üzerindeki etkilerine yönelik deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.1.1', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Ampullerin bağlanma durumunun ampul parlaklığına etkisine yönelik deney yapabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.1.2', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Elektrik akımını tanımlayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.1.3', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Bir devre elemanının uçları arasındaki potansiyel farkı (gerilimi) tanımlayabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.1.4', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Bir devre elemanının uçları arasındaki gerilim ile üzerinden geçen akım ilişkisine yönelik tümevarımsal akıl yürütebilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.1.5', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Özgün bir aydınlatma aracı modeli oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.2.1', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Elektrik enerjisinin dönüştüğü enerjileri sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.2.2', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Elektrik enerjisinin ısı, ışık, ses veya hareket enerjisine dönüşümüne yönelik bir model oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.2.3', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Elektrik enerjisi üretim santrallerini sınıflandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.2.4', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Elektrik enerjisi üretim santrallerinin avantaj ve dezavantajlarını tartışabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.6.2.5', 8, 6, 'ELEKTRİĞİN YOLCULUĞU', 'Elektrik enerjisinin bilinçli ve tasarruflu kullanılmasının önemini tartışabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.7.1.1', 8, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE MADDE DÖNGÜLERİ', 'Bitkilerde besin üretiminde fotosentezin önemini yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.7.1.2', 8, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE MADDE DÖNGÜLERİ', 'Fotosentez hızını etkileyen faktörler ile ilgili hipotez oluşturabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.7.1.3', 8, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE MADDE DÖNGÜLERİ', 'Canlılarda solunumun önemini yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.7.2.1', 8, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE MADDE DÖNGÜLERİ', 'Öğrencilerin madde döngülerinin önemi ile ilgili tartışmaları sağlanabilir. Tartışma sırasında Türkçe dersinde yer alan iletişim becerilerinden faydalanılabilir. Su, oksijen ve karbon döngülerinin şemalarını gösteren model, poster, video, animasyon vb. ile öğrencilerin', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.7.2.2', 8, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE MADDE DÖNGÜLERİ', 'Madde döngülerinin yaşam açısından önemini yapılandırabilme', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.7.2.3', 8, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE MADDE DÖNGÜLERİ', 'Küresel iklim değişikliğinin nedenlerini ve olası sonuçlarını içeren örnek olay senaryosu üzerinden beyin fırtınası tekniği yaptırılabilir. Küresel iklim değişikliğinin olası sonuçlarının insan ve çevre üzerindeki etkileri konusunda öğrencilerin dijital, basılı ve görsel kaynaklar', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu'),
  (fb_id, 'FB.8.7.2.4', 8, 7, 'SÜRDÜRÜLEBİLİR YAŞAM VE MADDE DÖNGÜLERİ', 'Öğrencilere ülkemizdeki küresel iklim değişikliğinin sebep olduğu çevre sorunlarını konu alan görsel, haber, belgesel vb. sunularak çevre sorunlarına vurgu yapılır. Öğrencilerin çevre sorunları ile ilgili merak ettikleri soruları sormaları istenir (E3.8). Dijital, yazılı ve', NULL, 'Fen Bilimleri', 'ortaokul', 'zorunlu');

  RAISE NOTICE 'Fen Bilimleri sinif 5-8: % kayıt eklendi', 143;
END $$;