-- Migration 035: İHL tam kazanım seed
-- Tüm 21 IHL PDFinden çıkarılan 469 kazanım
-- ON CONFLICT DO UPDATE → migration 025 partial seed üzerine güvenli yazma

INSERT INTO kazanimlar (kod, brans_id, sinif, unite_no, unite_ad, ad, aciklama, ders, okul_tipi, ders_turu)
SELECT v.kod, b.id, v.sinif::integer, v.unite_no::integer, v.unite_ad, v.ad,
       v.aciklama, v.ders, v.okul_tipi, v.ders_turu
FROM (VALUES
  ('AKD.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Öğrencilerden akaid ilminin konusu ve amaçlarını fark edebilmeleri için bu ilimle ilgili araş-', '', 'Akaid', 'ihl', 'zorunlu'),
  ('AKD.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'İman ve imanın mahiyetiyle ilgili konuları müşahede edebilme', '', 'Akaid', 'ihl', 'zorunlu'),
  ('AKD.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Allah’ın (cc) varlığı ve birliği konusuyla fıtrat arasındaki ilişki açıklanır. İnancın fıtriliği üzerin-', '', 'Akaid', 'ihl', 'zorunlu'),
  ('AKD.11.2.2', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Kader inancını idrak edebilme', '', 'Akaid', 'ihl', 'zorunlu'),
  ('AKD.11.2.3', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Kaderle ilişkilendirilen kavramları çözümleyebilme', '', 'Akaid', 'ihl', 'zorunlu'),
  ('AKD.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Öğrencilerden peygamberlikle ilişkili olduğunu düşündükleri kavramları listelemeleri istenir', '', 'Akaid', 'ihl', 'zorunlu'),
  ('AKD.11.3.2', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Öğrencilere peygamberlere gönderilen kitaplar konusunda doğru bilgilere nereden ula-', '', 'Akaid', 'ihl', 'zorunlu'),
  ('AKD.11.4.1', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Meleklere iman konusunda bilgi alınabilecek güvenilir kaynaklar öğretmen rehberliğinde', '', 'Akaid', 'ihl', 'zorunlu'),
  ('AKD.11.4.2', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Dünya hayatı ve ahiret ilişkisini yorumlayabilme', '', 'Akaid', 'ihl', 'zorunlu'),
  ('AKD.11.4.3', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Ahiret hayatının safhalarını özetleyebilme', '', 'Akaid', 'ihl', 'zorunlu'),
  ('ARP.9.1.1', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', '9.1.1.1. Selamlaşma ve tanışmayla ilgili dinlemeye/izlemeye hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.1.2', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'Öğrencilerin ön bilgi ve deneyimleri, konuyla ilgili soru sorma, görseller sunma, ana dilde kulla-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.1.3', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'Mevcut içerik dinletilerek/izletilerek öğrencilerin hedef dilin yapısına aşinalık kazanmaları sağ-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.1.4', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'Öğrencilerin üniteyle ilgili önemli kelime ve ifadeleri tanımaları için ünite içerikleri dinletilir/', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.1.5', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', '9.1.5.1. Hedef harfleri ve harekeleri sesletim unsurlarına uygun olarak seslendirebilme', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.1.6', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'Dinleme/izleme ve okuma aşamalarını tamamlayan öğrencilerin mevcut içerikle ilişki kur-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.1.7', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'Öğretmen tarafından müstakil harfler ve harekeler yazı yönü ve satır konumuna dikkat', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.2.1', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Öğrencilerin ön bilgi ve deneyimleri, konuyla ilgili soru sorma, görseller sunma, ana dilde kul-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.2.2', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Öğrencilerin ön bilgi ve deneyimleri, konuyla ilgili soru sorma, görseller sunma, ana dilde kulla-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.2.3', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', '9.2.3.1. Okul ve sınıfla ilgili dinlediği/izlediği içerikteki hedef dil yapılarını kullanabilme', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.2.4', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Öğrencilerin üniteyle ilgili önemli kelime ve ifadeleri tanımaları için ünite içerikleri dinletilir/', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.2.5', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Dinleme/izleme ve okuma aşamalarını tamamlayan öğrencilerin mevcut içerikle ilişki kur-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.2.6', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Dinleme/izleme, okuma ve konuşma aşamalarını tamamlayan öğrencilerin önceki bilgi ve', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.3.1', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', '9.3.1.1. Aile ve evle ilgili dinlemeye/izlemeye hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.3.2', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', 'Öğrencilerin ön bilgi ve deneyimleri, konuyla ilgili soru sorma, görseller sunma, ana dilde kulla-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.3.3', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', 'Mevcut içerik dinletilerek/izletilerek öğrencilerin hedef dilin yapısına aşinalık kazanmaları', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.3.4', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', 'Öğrencilerin üniteyle ilgili önemli kelime ve ifadeleri tanımaları için ünite içerikleri dinletilir/', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.3.5', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', 'Dinleme/izleme ve okuma aşamalarını tamamlayan öğrencilerin mevcut içerikle ilişki kur-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.3.6', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', 'Dinleme/izleme, okuma ve konuşma aşamalarını tamamlayan öğrencilerin önceki bilgi ve', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.4.1', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', '9.4.1.1. Günlük hayatla ilgili dinlemeye/izlemeye hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.4.2', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'Öğrencilerin ön bilgi ve deneyimleri, konuyla ilgili soru sorma, görseller sunma, ana dilde kulla-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.4.3', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', '9.4.3.1. Günlük hayatla ilgili dinlediği/izlediği içerikteki hedef dil yapılarını kullanabilme', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.4.4', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'Öğrencilerin üniteyle ilgili önemli kelime ve ifadeleri tanımaları için ünite içerikleri dinletilir/', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.4.5', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'Dinleme/izleme ve okuma aşamalarını tamamlayan öğrencilerin mevcut içerikle ilişki kur-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.9.4.6', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'Dinleme/izleme, okuma ve konuşma aşamalarını tamamlayan öğrencilerin önceki bilgi ve', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.1.1', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', '10.1.1.1. Akrabalar ve güzel davranışlarla ilgili dinlemeye/izlemeye hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.1.2', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Öğrencilerin ön bilgi ve deneyimleri, konuyla ilgili soru sorma, görseller sunma, ana dil-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.1.5', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Dinleme/izleme ve okuma aşamalarını tamamlayan öğrencilerin mevcut içerikle ilişki kur-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.1.3', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Mevcut içerik dinletilerek/izletilerek öğrencilerin hedef dilin yapısına aşinalık kazanmaları', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.1.4', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Öğrencilerin üniteyle ilgili önemli kelime ve ifadeleri tanımaları için ünite içerikleri dinletilir/', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.1.6', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Dinleme/izleme, okuma ve konuşma aşamalarını tamamlayan öğrencilerin önceki bilgi ve', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.2.1', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'a) 	 Önceki bilgi ve deneyimleri harekete geçirir.', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.2.2', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Öğrencilerin ön bilgi ve deneyimleri, konuyla ilgili soru sorma, görseller sunma, ana dilde kulla-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.2.5', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Dinleme/izleme ve okuma aşamalarını tamamlayan öğrencilerin mevcut içerikle ilişki kur-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.2.3', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Mevcut içerik dinletilerek/izletilerek öğrencilerin hedef dilin yapısına aşinalık kazanmaları', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.2.4', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Öğrencilerin üniteyle ilgili önemli kelime ve ifadeleri tanımaları için ünite içerikleri dinletilir/', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.2.6', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Dinleme/izleme, okuma ve konuşma aşamalarını tamamlayan öğrencilerin önceki bilgi ve', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.3.1', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', '10.3.1.1. Seyahat ve ulaşım araçlarıyla ilgili dinlemeye/izlemeye hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.3.3', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', '10.3.3.1. Seyahat ve ulaşım araçlarıyla ilgili dinlediği/izlediği içerikteki hedef dil yapılarını', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.3.4', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Öğrencilerin üniteyle ilgili önemli kelime ve ifadeleri tanımaları için ünite içerikleri dinletilir/', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.3.5', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Dinleme/izleme ve okuma aşamalarını tamamlayan öğrencilerin mevcut içerikle ilişki kur-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.3.6', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Dinleme/izleme, okuma ve konuşma aşamalarını tamamlayan öğrencilerin önceki bilgi ve', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.3.2', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Öğrencilerin ön bilgi ve deneyimleri, konuyla ilgili soru sorma, görseller sunma, ana dilde kulla-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.4.1', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', '10.4.1.1. Mevsimler ve alışverişle ilgili dinlemeye/izlemeye hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.4.2', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Öğrencilerin ön bilgi ve deneyimleri, konuyla ilgili soru sorma, görseller sunma, ana dil-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.4.3', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Mevcut içerik dinletilerek/izletilerek öğrencilerin hedef dilin yapısına aşinalık kazanmaları', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.4.4', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Öğrencilerin üniteyle ilgili önemli kelime ve ifadeleri tanımaları için ünite içerikleri dinletilir/', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.4.5', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Dinleme/izleme ve okuma aşamalarını tamamlayan öğrencilerin mevcut içerikle ilişki kur-', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('ARP.10.4.6', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Dinleme/izleme, okuma ve konuşma aşamalarını tamamlayan öğrencilerin önceki bilgi ve', '', 'Mesleki Arapça', 'ihl', 'zorunlu'),
  ('DE.1.1', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Din eğitimi ile ilgili temel kavramları bağlamına uygun kullanabilme', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.1.2', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Din eğitimi biliminin önemi ve gerekliliği konusunda analitik düşünebilme', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.2.1', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Gelişim dönemlerine göre din eğitimi uygulamalarını sınıflandırabilme', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.2.2', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Gelişim dönemlerinde dinî anlayışı etkileyen unsurları özetleyebilme', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.2.3', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Gençlik dönemi kimlik inşasında dinin etkisini müşahede edebilme', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.3.1', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Değer temelli ahlak eğitiminin önemini anlayabilme', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.3.2', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Çevresel unsurların ahlak ve değer eğitimindeki rolünü yorumlayabilme', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.3.3', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Ahlak ve değer eğitimi yaklaşımlarını temel alan din eğitimi uygulamaları hakkında', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.4.1', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Türkiye’de yürütülen örgün din eğitimi uygulamalarını yapılandırabilme', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.4.2', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Türkiye’de yürütülen yaygın din eğitimi örneklerini mesleki olarak uygulayabilme', '', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DM.9.1.1', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Türk musikisinde kullanılan temel yazı, işaret ve kavramları', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.1.2', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Dinî musikide kullanılan basit makamları sınıflandırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.1.3', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Türk din musikisine katkı sağlayan Hatib Zâkirî Hasan Efendi hakkında', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.1.4', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Türk din musikisinde kullanılan ney ve kudüm çalgılarını', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.1.5', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Nim sofyan usulüne uygun hareket edebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.1.6', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Rast makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.2.1', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Türk-İslam musikisinin tarihsel gelişimi hakkında bilgi toplayabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.2.2', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Türk din musikisine katkı sağlayan Buhurizade Mustafa Itrî hakkında bilgi', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.2.3', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Türk din musikisinde kullanılan kanun ve bendir çalgılarını karşılaştırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.2.4', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Semai usulüne uygun hareket edebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.2.5', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Uşşak makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.2.6', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Hüseyni makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.3.1', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Türk din musikisinde kullanılan formları sınıflayabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.3.2', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Türk din musikisine katkı sağlayan Hammâmîzade İsmail Dede Efendi', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.3.3', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Türk din musikisinde kullanılan tambur ve klasik kemençeyi', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.3.4', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Sofyan usulüne uygun hareket edebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.9.3.5', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Hicaz makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.1.1', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Türk musikisinde kullanılan temel yazı, işaret ve kavramları', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.1.2', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Dinî musikide kullanılan göçürülmüş (şed) makamları sınıflandırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.1.3', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Türk din musikisine katkı sağlayan Zekai Dede hakkında bilgi toplayabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.1.4', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Türk din musikisinde kullanılan ut ve tef çalgılarının karşılaştırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.1.5', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Türk aksağı usulüne uygun hareket edebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.1.6', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Nihavent makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.2.1', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'İslam ülkelerindeki dinî musiki uygulamaları hakkında bilgi toplayabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.2.2', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Türk din musikisine katkı sağlayan Ali Ufki hakkında bilgi toplayabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.2.3', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Türk din musikisinde kullanılan santur ve rebap çalgılarını karşılaştırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.2.4', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Yürük semai usulüne uygun hareket edebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.2.5', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Acemaşiran makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.3.1', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Türk din musikisinde kullanılan formları sınıflandırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.3.2', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Türk din musikisine katkı sağlayan Hafız Post hakkında bilgi toplayabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.3.3', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Türk din musikisinde kullanılan mey ve bağlama çalgılarını', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.3.4', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Devrihindi usulüne uygun hareket edebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.10.3.5', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Muhayyerkürdi makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Türk musikisinde kullanılan temel yazı, işaret ve kavramları', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Dinî musikide kullanılan bileşik (mürekkeb) makamları sınıflandırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.1.3', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Türk din musikisine katkı sağlayan Cinuçen Tanrıkorur hakkında bilgi', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.1.4', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Farklı kültürlere ait musiki çalgılarından erhu ve viyolonseli', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.1.5', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Düyek ve müsemmen usullerine uygun hareket edebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.1.6', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Segâh makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Dinî musikinin psikolojik, kültürel ve toplumsal işlevlerini tartışabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.2.2', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Türk din musikisine katkı sağlayan Sadettin Kaynak hakkında bilgi', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.2.3', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Farklı kültürlere ait piyano ve sitar çalgılarını karşılaştırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.2.4', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Aksak usulüne uygun hareket edebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.2.5', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Saba makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Türk din musikisinde kullanılan diğer formları sınıflandırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.3.2', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Türk din musikisine katkıları olan toplulukları sentezleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.3.3', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Türk din musikisine katkı sağlayan Hâce Muhammed Lutfi hakkında bilgi', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.3.4', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Farklı kültürlere ait bansuri ve yan flüt çalgılarını karşılaştırabilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.3.5', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Curcuna usulüne uygun hareket edebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DM.11.3.6', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Hüzzam makamını dinleyebilme', '', 'Dini Musiki', 'ihl', 'secmeli'),
  ('DT.12.1.1', 'ihl_meslek_dersleri', 12, 1, 'Ünite 1', 'Öğretmen tarafından din bilimcilerin din tanımlarına yer verilerek felsefe, sosyoloji, psikoloji', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('DT.12.1.2', 'ihl_meslek_dersleri', 12, 1, 'Ünite 1', 'Öğrenciler, öğretmen rehberliğinde dinler tarihinin gelişim süreciyle ilgili bilgi edinebile-', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('DT.12.2.1', 'ihl_meslek_dersleri', 12, 2, 'Ünite 2', 'Öğretmen tarafından İslamiyet’in doğduğu coğrafya ve kültürel ortam hakkında kısaca bil-', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('DT.12.2.2', 'ihl_meslek_dersleri', 12, 2, 'Ünite 2', 'İslam’ın inanç esasları, ibadetleri ve ahlaki ilkelerini anlayabilme', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('DT.12.2.3', 'ihl_meslek_dersleri', 12, 2, 'Ünite 2', 'Öğrencilerin İslam’ın diğer dinlere bakışıyla ilgili merak ettikleri konuları belirlemeleri sağla-', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('DT.12.3.1', 'ihl_meslek_dersleri', 12, 3, 'Ünite 3', 'Öğretmen tarafından İbrani, İsrail, Yahudi ve Musevi kavramlarına değinilerek Yahudiliğin ta-', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('DT.12.3.2', 'ihl_meslek_dersleri', 12, 3, 'Ünite 3', 'Öğretmen tarafından Hint dinleri hakkında kısaca bilgi verilir. Bu dinlerden biri olan Hin-', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('DT.12.4.1', 'ihl_meslek_dersleri', 12, 4, 'Ünite 4', 'Öğretmen tarafından misyon kavramı açıklanır. Öğrencilerin bu kavramdan hareketle', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('DT.12.4.2', 'ihl_meslek_dersleri', 12, 4, 'Ünite 4', 'Öğrencilerden Bahailiğin tarihî süreci ve temel özellikleriyle ilgili merak ettikleri konuları', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('DT.12.4.3', 'ihl_meslek_dersleri', 12, 4, 'Ünite 4', 'Yapılandırılmış metinden hareketle öğrencilerin yeni dinî hareketleri fark etmeleri sağlanır.', '', 'Dinler Tarihi', 'ihl', 'zorunlu'),
  ('EB.9.1.1', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Ebru sanatını ve bu sanatın tarihî gelişimini yorumlayabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.1.2', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Tarihimizdeki bazı meşhur ebrucuların ebru sanatına katkılarını', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.2.1', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Ebru sanatında kullanılan malzemeleri işlevlerine göre sınıflandırabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.3.1', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Zemin ebrusunun özelliklerini özetleyebilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.3.2', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Zemin ebrusu yapabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.4.1', 'ihl_meslek_dersleri', 9, 4, 'Düzey I - Ünite 4', 'Battal ebruyu özetleyebilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.4.2', 'ihl_meslek_dersleri', 9, 4, 'Düzey I - Ünite 4', 'Battal ebru türlerini yapabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.5.1', 'ihl_meslek_dersleri', 9, 5, 'Düzey I - Ünite 5', 'Battal ile başlanan ebru türlerini karşılaştırabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.5.2', 'ihl_meslek_dersleri', 9, 5, 'Düzey I - Ünite 5', 'Battal ile başlanan ebru türlerini yapabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.6.1', 'ihl_meslek_dersleri', 9, 6, 'Düzey I - Ünite 6', 'Hatip ebrularını karşılaştırabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.9.6.2', 'ihl_meslek_dersleri', 9, 6, 'Düzey I - Ünite 6', 'Hatip ebrularını yapabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.10.1.1', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Ebru sanatının geleneğini çözümleyebilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.10.1.2', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Ebru sanatının diğer sanatlarla ilişkisini gözlemleyebilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.10.2.1', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Çiçekli ebruları özetleyebilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.10.2.2', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Lale, karanfil, sümbül ebrularını yapabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.10.3.1', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Menekşe, papatya, gelincik ebrularını karşılaştırabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.10.3.2', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Menekşe, papatya, gelincik ebrularını yapabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Kumlu ebru türlerini karşılaştırabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Kumlu ebru çeşitlerini yapabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Yazılı akkâse ebruları özetleyebilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.11.2.2', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Yazılı akkâse ebru yapabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Türk ebrusunun kullanım yerlerini özetleyebilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.11.3.2', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Türk ebru sanatında murakka ve mühre yapabilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('EB.11.3.3', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Türk ebrusunda tasarım unsurlarını çözümleyebilme', '', 'Ebru', 'ihl', 'secmeli'),
  ('FKH.10.1.1', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Fıkıh ilminin tanımı, amacı, önemi, konusu ve fıkıh-usul ilişkisi açıklanır. Usul ve fakih', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.1.2', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Fıkıh ilminin temel ilkelerine dair bilgi verilir. Temel ilkelerin gelişmeye açıklık, tekliflerde', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.1.3', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Fıkıh ilminin tarihi ile ilgili zamanı algılayabilme ve kronolojik düşünebilme', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.1.4', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Fıkhi mezheplerin oluşumundan sonraki gelişmeleri özetleyebilme', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.2.1', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Fıkıh usulünün konuları arasında yer alan ehliyet, mükellef ve hüküm kavramları açıklana-', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.2.2', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Fıkhi hükümlerin delilleri ve yöntemleri ile ilgili dinî kavramları bağlamına uy-', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.3.1', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Namaz ibadetini usulüne uygun olarak tatbik edebilme', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.3.2', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Oruç ile ilgili deneyimlerini yansıtabilme', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.3.3', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Zekâtın hükümlerini sentezleyebilme', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.3.4', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Ayet ve hadislerden yararlanarak hac ibadeti, hac ibadetinin ifası, bireysel ve toplumsal', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.3.5', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Cihat konusu ile ilgili kavramlar ve cihadın mahiyeti ele alınır. Cihadın bireysel ve toplumsal', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.4.1', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Ailenin toplumun temeli olduğu vurgulanır. Öğrencilerin İslam’ın aile kurumuna verdiği', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.4.2', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'İslam’da helal kazancın önemine vurgu yapılır. Riba kavramına değinilir. Faiz yasağı, sigorta-', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.4.3', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Helaller ve haramlarla ilgili dinî meseleleri anlayabilme', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('FKH.10.4.4', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'İslam ceza hukuku ile ilgili konuları özetleyebilme', '', 'Fıkıh', 'ihl', 'zorunlu'),
  ('HDS.10.1.1', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Hadis ilminin konusunu ve önemini çözümleyebilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.1.2', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Hadis ilmiyle ilgili kavramları sınıflandırabilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.1.3', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Sünnetin dindeki yeri ve bağlacılığıyla ilgili sentez yapabilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.1.4', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Hz. Muhammed’in (sav) nübüvvetinin özelliklerine değinilir. Bu özellikler arasında onun', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.1.5', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Kur’an ve sünnete bağlılıkla ilgili bir hadisişerifin anlamı, hadisin sahabi ravisi de tanıtılarak', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.2.1', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Hadislerin sözlü ve yazılı aktarımını tarihsel bağlamsallaştırabilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.2.2', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Hadislerin tedvin ve tasnif sürecini karşılaştırabilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.2.3', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Tedvin ve tasnif sonrası hadis çalışmalarını özetleyebilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.2.4', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Öğrencilerden, imanla ilgili hadisleri güvenilir hadis kaynaklarından  tespit etmeleri istenir.', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.2.5', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'İman ile ilgili bir hadisişerifin anlamı, hadisin sahabi ravisi de tanıtılarak açıklanır. Hadis', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.3.1', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Kaynağına göre hadis çeşitlerini sınıflandırabilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.3.2', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Ravi sayısına göre hadis çeşitlerini ayırt edebilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.3.3', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Sıhhat derecesine göre hadis çeşitlerini özetleyebilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.3.4', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Ahlakla ilgili hadis rivayetlerinde hadis kaynaklarına başvurabilme', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.3.5', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Ahlak ile ilgili bir hadisişerifin anlamı, hadisin sahabi ravisi de tanıtılarak açıklanır. Hadis usu­', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.4.1', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Hadis ve sünnetin anlaşılmasını konu alan ilimlerle ilgili örnek olay ve durumlar açıklanır.', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.4.2', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Hadis ve sünnetin anlaşılmasında kullanılan esaslar incelenerek hadis ve sünnet ile bu', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.4.4', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'İlimle ilgili seçilen bir hadisişerifin anlamı ve hadisi rivayet eden sahabi tanıtılarak açıklanır.', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HDS.10.4.3', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Öğrencilerin güvenilir hadis kaynaklarından ilimle ilgili hadisleri tespit etmeleri sağlanır. Ha­', '', 'Hadis', 'ihl', 'zorunlu'),
  ('HMU.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Ülkemizdeki din hizmetlerini müşahede edebilme', '', 'Hitabet ve Mesleki Uygulama', 'ihl', 'zorunlu'),
  ('HMU.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'İletişim ve hitabet kavramları açıklanarak etkili iletişim hakkında bilgi verilir. Din', '', 'Hitabet ve Mesleki Uygulama', 'ihl', 'zorunlu'),
  ('HMU.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Vaazı usulüne uygun olarak yerine getirebilme', '', 'Hitabet ve Mesleki Uygulama', 'ihl', 'zorunlu'),
  ('HMU.11.2.2', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Hutbe, hatip, mihrap ve minber kavramları açıklanır. Öğrenciler, hutbeyi diğer dinî hitabet', '', 'Hitabet ve Mesleki Uygulama', 'ihl', 'zorunlu'),
  ('HMU.11.2.3', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Öğrencilerden çocukluk dönemlerindeki inanç ve ibadetle ilgili yaşantılarını paylaşmaları', '', 'Hitabet ve Mesleki Uygulama', 'ihl', 'zorunlu'),
  ('HMU.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Cami musikisi örneklerini usulüne uygun biçimde yerine getirebilme', '', 'Hitabet ve Mesleki Uygulama', 'ihl', 'zorunlu'),
  ('HMU.11.3.2', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Ayet ve hadislerden örnekler verilerek duanın önemi üzerinde durulur. Dua örnekleri “ezan,', '', 'Hitabet ve Mesleki Uygulama', 'ihl', 'zorunlu'),
  ('HMU.11.4.1', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Sosyal yaşamda yer alan dinî merasimleri usulüne uygun biçimde yerine', '', 'Hitabet ve Mesleki Uygulama', 'ihl', 'zorunlu'),
  ('HMU.11.4.2', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Ayet ve hadislerden örnekler verilerek dünya hayatının geçiciliğine ve ölümün hakikat', '', 'Hitabet ve Mesleki Uygulama', 'ihl', 'zorunlu'),
  ('HN.9.1.1', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Hüsnühattın tanımı ve gayesi hakkında bilgi toplayabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.1.2', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Hüsnühattın malzemeleri ve kullanım alanlarını çözümleyebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.1.3', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Hüsnühatta malzeme kalitesinin önemini yansıtabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.2.1', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Hüsnühat meşk usulü ve icazet hakkında bilgi toplayabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.2.2', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Hattatlığın şartlarını çözümleyebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.2.3', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Hüsnühat öğrenmenin faydaları hakkında bilgi toplayabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.2.4', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Rika harfleriyle meşk murakkasındaki örneklere uygun şekilde sanat eseri', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.3.1', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Hüsnühattın ortaya çıkış ve gelişim sürecini özetleyebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.3.2', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Hüsnühatta kullanılan yazı çeşitleri hakkında bilgi toplayabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.3.3', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Meşhur hattatlardan bazıları ve Türklerin hat sanatına hizmetleri hakkında bilgi', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.3.4', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Rika harflerinin birleşimleriyle meşk murakkasındaki örneklere uygun şekilde', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.4.1', 'ihl_meslek_dersleri', 9, 4, 'Düzey I - Ünite 4', 'Kullanım alanlarına göre hüsnühat eserleriyle ilgili bilgi toplayabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.4.2', 'ihl_meslek_dersleri', 9, 4, 'Düzey I - Ünite 4', 'Rika kelime ve cümleleriyle meşk murakkasındaki örneklere uygun şekilde', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.5.1', 'ihl_meslek_dersleri', 9, 5, 'Düzey I - Ünite 5', 'Yazılacak rika metnine  karar verebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.5.2', 'ihl_meslek_dersleri', 9, 5, 'Düzey I - Ünite 5', 'Rika metnini hüsnühat ile yazarak sanatsal eser oluşturabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.9.5.3', 'ihl_meslek_dersleri', 9, 5, 'Düzey I - Ünite 5', 'Rika eserinin bezenmesi ve çerçeveletilmesiyle sanatsal ürün oluşturabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.1.1', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Hüsnühat malzemelerinin hazırlanma sürecini çözümleyebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.1.2', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Sülüs “Rabbi yessir…” metniyle meşk murakkasındaki örneklere uygun şekilde', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.2.1', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Hat sanatının tarihini özetleyebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.2.2', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Sülüs harfleri ve be birleşimleriyle meşk murakkasındaki örneklere uygun', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.3.1', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Sanat-estetik ilişkisiyle ilgili bilgi toplayabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.3.2', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Hüsnühattın estetik kriterlerini özetleyebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.3.3', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Hüsnühatla diğer güzel sanatları karşılaştırabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.3.4', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Sülüs cim ve sin birleşimleriyle meşk murakkasındaki örneklere uygun şekilde', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.4.1', 'ihl_meslek_dersleri', 10, 4, 'Düzey II - Ünite 4', 'Yazılacak metne karar verebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.4.2', 'ihl_meslek_dersleri', 10, 4, 'Düzey II - Ünite 4', 'Metni hüsnühat ile yazarak sanatsal eser oluşturabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.10.4.3', 'ihl_meslek_dersleri', 10, 4, 'Düzey II - Ünite 4', 'Hüsnühat eserinin bezenmesi ve çerçeveletilmesiyle sanatsal ürün oluşturabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Kalem ve harf bünyeleriyle ilgili kavramlar, harfler haricindeki unsurlar', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Sülüs sad ve tı harflerinin birleşimleriyle meşk murakkasındaki örneklere', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Kitap, mimari, levha ve diğer alanlarda hüsnühattın kullanımını gözlemleyebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.11.2.2', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Sülüs ayn, fe ve kef harflerinin birleşimlerini meşk murakkasındaki örneklere', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Hat sanatının diğer ilim ve sanat dallarıyla olan ilişkisini yapılandırabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.11.3.2', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Sülüs mim ve he harflerinin birleşimleri ve temmet metniyle meşk', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.11.4.1', 'ihl_meslek_dersleri', 11, 4, 'Düzey III - Ünite 4', 'Yazılacak sülüs metnine  karar verebilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.11.4.2', 'ihl_meslek_dersleri', 11, 4, 'Düzey III - Ünite 4', 'Sülüs metnini hüsnühat ile yazarak sanatsal eser oluşturabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('HN.11.4.3', 'ihl_meslek_dersleri', 11, 4, 'Düzey III - Ünite 4', 'Sülüs eserinin bezenmesi ve çerçeveletilmesiyle sanatsal ürün oluşturabilme', '', 'Hüsnühat', 'ihl', 'secmeli'),
  ('İÇE.1.1', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', '“Sorumluluk üç kişiden kaldırılmıştır: Aklı erin­', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.1.2', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'İslam’da çocuk eğitimi yaklaşımlarını yorumlayabilme', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.1.3', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'İslam’da çocuk eğitiminde ailenin önemini müşahede edebilme', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.1.4', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Gelişim alanlarını özetleyebilme', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.2.1', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Çocukta inanç gelişim özelliklerini yorumlayabilme', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.2.2', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Çocuğun inanç gelişimini etkileyen faktörleri müşahede edebilme', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.2.3', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Çocuğun gelişimine göre inanç esaslarının öğretimini tatbik edebilme', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.3.1', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Çocuğun gelişim özelliklerine göre ibadet algısını müşahede edebilme', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.3.2', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Çocuğun gelişimine göre ibadet eğitimini tatbik edebilme', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.4.1', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Çocukta ahlak gelişim dönemlerini müşahede edebilme.', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.4.2', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'kopmadan dönüştürür.', '', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İBT.1.1', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', '  İslam biliminin temel kavramları ve ge-', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.2', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', '  İslam’ın doğduğu ortamın kültürel, ekonomik ve dinî özelliklerini sentezleyebil-', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.3', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', '  İslam dünyasında bilimin gelişmesinde etkili olan unsurları yorumlayabilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.4', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', '  Şehirlerin bilim, sanat ve irfana etkisi ile ilgili bilgi toplayabilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.5', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', '  İslami ilimlerin oluşumunu kaynağından inceleyebilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.6', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', '  Teoriden pratiğe İslam dünyasında bilime yönelik ilk çalışma alanları ile ilgili çı-', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.7', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', '  İslam dünyasında tercüme faaliyetlerinin nedenlerini sorgulayabilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.8', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', '  Bilim alanlarını yeniden sınıflandırabilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.1', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', '  Yeni siyasi, iktisadi, kültürel yapılanma ve ilim merkezlerinin oluşumu ile ilgili', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.2', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', '  İslam dünyasında ilk medreselerin kuruluş nedenlerini sorgulayabilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.3', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', '  İslam bilim tarihinde gözlem ve deneye yönelimi tarihsel bağlamsallaştırma ile', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.4', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', '  İslam dünyasında gök bilimi, matematik, fen, sağlık bilimleri ve sosyal bilimler', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.5', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', '  İslam dünyasında yapılan teknik ürünlerle ilgili analojik akıl yürütebilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.3.1', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', '  Endülüs Bilim Havzası’nda yapılan bilimsel çalışmalar ile ilgili kaynaklardan bilgi', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.3.2', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', '  Harita üzerinden İslam biliminin Avrupa’ya geçiş yolları ile ilgili çıkarım yapabilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.3.3', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', '  İslam biliminin Avrupa’da yeni bir medeniyetin doğuşuna etkisini yorumlayabilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.4.1', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', '  Türkistan Bilim Havzası’ndaki bilimsel çalışmaları tarihsel bağlamda değerlen-', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.4.2', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', '  Haçlı saldırılarının bilimin Batı’ya geçişindeki etkilerini yapılandırabilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.4.3', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', '  Büyük Selçuklular, Birinci Beylikler ve Türkiye Selçukluları Dönemi bilimsel ça-', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.1', 'ihl_meslek_dersleri', 11, 5, 'Ünite 5', '  Erken Dönem Osmanlı bilim anlayışının oluşumunu ve Türkçenin bilim dili hâline', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.2', 'ihl_meslek_dersleri', 11, 5, 'Ünite 5', '  İstanbul’un bilim merkezi hâline gelme sürecindeki unsurları yapılandırabilme', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.3', 'ihl_meslek_dersleri', 11, 5, 'Ünite 5', '  Takıyyüddin Rasıd ve İstanbul Rasathanesinin açılışı ve yapılan çalışmalar ile il-', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.4', 'ihl_meslek_dersleri', 11, 5, 'Ünite 5', '  Osmanlı Devleti’nde coğrafya, haritacılık, kartografya ve tıp alanında yapılan ça-', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.5', 'ihl_meslek_dersleri', 11, 5, 'Ünite 5', '  Osmanlı Devleti’nde yeni eğitim kurumlarının açılış nedenlerini ve yeni bilimsel', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.6', 'ihl_meslek_dersleri', 11, 5, 'Ünite 5', '  XVIII-XIX. yüzyılda eğitim ve bilim alanında faaliyet gösteren bilim insanlarının', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.7', 'ihl_meslek_dersleri', 11, 5, 'Ünite 5', '  Osmanlı Devleti’nde modern yapılanmanın ve Rasathâne-i Âmire’de yapılan ça-', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.6.1', 'ihl_meslek_dersleri', 11, 6, 'Ünite 6', '  Cumhuriyet Dönemi bilim politikalarını ve yeni kurulan bilim kurumlarının çalış-', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.6.2', 'ihl_meslek_dersleri', 11, 6, 'Ünite 6', '  Cumhuriyet Dönemi bilim insanlarının çalışmaları hakkında kaynaklardan bilgi', '', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İF.1.1', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'İslam felsefesiyle ilgili yapılan tanımlar', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.1.2', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'İslam felsefesinin gelişimine kaynaklık eden faktörleri özetleyebilme', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.1.3', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'İslam felsefesinin geliştiği ilim ve kültür havzalarıyla ilgili konuları müşahede ede-', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.1.4', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'İslam felsefesinin diğer disiplinlerle ilişkisini çözümleyebilme', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.2.1', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Varlık, bilgi ve ahlak konularını anlayabilme', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.3.1', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Meşşai felsefeyle ilgili konuları müşahede edebilme', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.3.2', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'İşrak felsefesi hakkında bilgi toplayabilme', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.4.1', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Endülüs’te yapılan İslam felsefesi çalışmalarını müşahede edebilme', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.4.2', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Osmanlı Dönemi İslam felsefesinin genel karakterini anlayabilme', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.4.3', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Yakın dönem İslam felsefesi çalışmalarını genelleyebilme', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.4.4', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'İslam felsefesinin Batı’ya etkisi konusunda eleştirel düşünebilme', '', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('KAK.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Tema 1', 'Kur’an-ı Kerim’in özellikleri ve isimleri hakkında bilgi toplayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Tema 1', 'Kur’an-ı Kerim’in içeriğini özetleyebilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.1.3', 'ihl_meslek_dersleri', 11, 1, 'Tema 1', 'Bakara suresinin 2. ayetini yorumlayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Tema 2', 'Allah’ın (cc) varlığı ve birliği ile ilgili akli ve naklî delilleri kullanabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.2.2', 'ihl_meslek_dersleri', 11, 2, 'Tema 2', 'Allah-âlem ilişkisiyle ilgili konuları sorgulayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.2.3', 'ihl_meslek_dersleri', 11, 2, 'Tema 2', 'Allah (cc) inancının hayata yansımalarını yorumlayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.2.4', 'ihl_meslek_dersleri', 11, 2, 'Tema 2', 'Allah-âlem ilişkisi konusunu incelerken Kur’an-ı Kerim meallerine', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Tema 3', 'İnsanın Kur’an-ı Kerim’de bildirilen sorumluluklarını idrak edebilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.3.2', 'ihl_meslek_dersleri', 11, 3, 'Tema 3', 'Kur’an-ı Kerim’den insan psikolojisiyle ilgili bilgi toplayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.3.3', 'ihl_meslek_dersleri', 11, 3, 'Tema 3', 'Müminlerin özellikleri hakkında Kur’an-ı Kerim meallerine başvurabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.4.1', 'ihl_meslek_dersleri', 11, 4, 'Tema 4', 'Kur’an-ı Kerim’de yer alan emir bilmaruf nehiy anilmünker, takva, zikir ve dua', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.11.4.2', 'ihl_meslek_dersleri', 11, 4, 'Tema 4', 'Araf suresinin 200-201. ayetlerini yorumlayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.1.1', 'ihl_meslek_dersleri', 12, 1, 'Tema 1', 'Kur’an-ı Kerim’in indirildiği ortam ile ilgili bilgi toplayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.1.2', 'ihl_meslek_dersleri', 12, 1, 'Tema 1', 'Kur’an-ı Kerim’in gönderiliş amacıyla ilgili görüşleri yapılandırabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.1.3', 'ihl_meslek_dersleri', 12, 1, 'Tema 1', 'Kur’an-ı Kerim’i anlamanın ve ona uygun yaşamanın önemini yorumlayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.1.4', 'ihl_meslek_dersleri', 12, 1, 'Tema 1', 'Yunus suresinin 57. ayetini yorumlayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.2.1', 'ihl_meslek_dersleri', 12, 2, 'Tema 2', 'Nübüvvet inancını özetleyebilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.2.2', 'ihl_meslek_dersleri', 12, 2, 'Tema 2', 'Peygamberlerin toplumsal dönüşümdeki rolünü yorumlayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.2.3', 'ihl_meslek_dersleri', 12, 2, 'Tema 2', 'Hz. Muhammed (sav) ile ilgili Kur’an-ı Kerim meallerine başvurabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.2.4', 'ihl_meslek_dersleri', 12, 2, 'Tema 2', 'Ahzab suresinin 45-46. ayetlerini tahlil edebilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.3.1', 'ihl_meslek_dersleri', 12, 3, 'Tema 3', 'Toplumu oluşturan unsurları sentezleyebilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.3.2', 'ihl_meslek_dersleri', 12, 3, 'Tema 3', 'Toplumu ayakta tutan ilkeleri çözümleyebilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.3.3', 'ihl_meslek_dersleri', 12, 3, 'Tema 3', 'İdeal toplumun (vasat ümmet) nasıl olması gerektiğini sorgulayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.3.4', 'ihl_meslek_dersleri', 12, 3, 'Tema 3', 'İsra suresinin 23. ayetini tahlil edebilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.4.1', 'ihl_meslek_dersleri', 12, 4, 'Tema 4', 'Ahiret ile ilgili konularda Kur’an-ı Kerim meallerine başvurabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.4.2', 'ihl_meslek_dersleri', 12, 4, 'Tema 4', 'Dünya ve ahiret hayatı hakkında mukayese yapabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KAK.12.4.3', 'ihl_meslek_dersleri', 12, 4, 'Tema 4', 'Enam suresinin 32. ayetini yorumlayabilme', '', 'Kur''an''ın Ana Konuları', 'ihl', 'secmeli'),
  ('KLM.12.1.1', 'ihl_meslek_dersleri', 12, 1, 'Ünite 1', 'Kelam ilminin mahiyetini müşahede edebilme', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KLM.12.1.2', 'ihl_meslek_dersleri', 12, 1, 'Ünite 1', 'Kelam ilminde doğru bilgi kaynakları olan haberisadık, aklıselim ve havassıselime hakkında', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KLM.12.1.3', 'ihl_meslek_dersleri', 12, 1, 'Ünite 1', 'Hz. Peygamber’in hayatta olduğu dönemde tartışılmayan bazı konuların, onun vefatından', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KLM.12.2.1', 'ihl_meslek_dersleri', 12, 2, 'Ünite 2', 'Din ve dinî yorum konuları açıklanarak itikat, mezhep ve tasavvuf kavramlarına değinilir.', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KLM.12.2.2', 'ihl_meslek_dersleri', 12, 2, 'Ünite 2', 'İtikadi ve siyasi mezheplerin özelliklerini mukayese yapabilme', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KLM.12.3.1', 'ihl_meslek_dersleri', 12, 3, 'Ünite 3', 'Allah’a (cc) ve kadere imanın temellendirilmesini yapılandırabilme', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KLM.12.3.2', 'ihl_meslek_dersleri', 12, 3, 'Ünite 3', 'Nübüvvet kavramı açıklanarak nübüvvetin imkânı ve gerekliliği konularına değinilir.', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KLM.12.3.3', 'ihl_meslek_dersleri', 12, 3, 'Ünite 3', 'Duyularla algılanamayan varlıkların öne çıkan özelliklerine ilişkin öğrencilerin görüşleri', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KLM.12.4.1', 'ihl_meslek_dersleri', 12, 4, 'Ünite 4', 'Yeni İlmikelam Dönemi’ne ve bu dönemdeki tartışma konularının neler olduğuna değinilir.', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KLM.12.4.2', 'ihl_meslek_dersleri', 12, 4, 'Ünite 4', 'Allah-insan-âlem ilişkisi hakkında ortaya çıkan yaklaşımlara dair öğrencilerin ön bilgilerini', '', 'Kelam', 'ihl', 'zorunlu'),
  ('KKIHL.9.2.1', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Harfleri telaffuz edebilme', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.1.1', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'Kur’an-ı Kerim’in terim anlamı verilir, gönderiliş amacı açıklanır. Kur’an-ı Kerim’i okumayı', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.1.2', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'Kıraat ilminin konuları arasında yer alan ayet, sure, hizip ve cüz kavramları açıklanır. Bu', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.1.3', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'Kur’an-ı Kerim’in Hz. Peygamber’e vahiy yoluyla nazil olduğu vurgulanır. Vahyin yazılması,', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.2.2', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Kur’an-ı Kerim alfabesindeki harflere ses özelliği kazandıran bazı özel işaretlerin olduğu', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.2.3', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Kur’an-ı Kerim’de özel okunuşa sahip kelimeler olduğu vurgulanarak elif lâm takısı, zamir,', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.2.4', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Meddin ortaya çıkmasına sebep olan harfimed ve sebebimed kavramları açıklanır. Sebe-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.2.5', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Öğrencilere tenvin konusu hatırlatılarak öğrenilecek kavram veya bilgiler önceki bilgileriy-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.2.6', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'Öğrencilere önceki öğrenmelerinden edindikleri tenvin ve sakin nun bilgisi hatırlatılarak', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.3.1', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', 'Fatiha, Bakara, Duha ila Hümeze surelerini yüzünden okuyabilme', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.4.1', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'Namaz dualarının anlamlarını yorumlayabilme', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.4.2', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'Namaz dualarını ezbere okuyabilme', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.4.3', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'Öğrencilerden Fatiha ve Fil ila Nâs surelerinin; Bakara suresi 1-5, 255, 285-286 ve Haşr', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.9.4.4', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'Ayet ve sureleri ezberlemenin Kur’an-ı Kerim öğretiminde özel bir yeri olduğu vurgulana-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.1.1', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Kur’an-ı Kerim’in gönderiliş amacını belirlemek için gruplar oluşturularak öğrencilerin gö-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.1.2', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Kur’an-ı Kerim öğretiminde temel ilke ve yöntemleri özetleyebilme', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.2.1', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Sakin mimin tanımı verilir. İdgam misleyn mealgunne, dudak ihfası ihfaişefevi ve sakin mi-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.2.2', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Kalkalenin tanımı, harfleri ve temel özellikleri ortaya konur. Kur’an-ı Kerim’den kalka-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.2.3', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', '“Ra” harfinin kelime içindeki yeri ve aldığı harekeye göre okunuşu ile ilgili kurallar açıkla-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.2.4', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Lafzatullah kavramı ve lafzatullahın okunuşu ile ilgili kurallar öğrencilere açıklanır. Lafza-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.2.5', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Kur’an-ı Kerim okumada zamirin okunuşuna ilişkin bazı kurallar üzerinde durulur. Zami-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.2.6', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Öğrencilere sekte kavramı örnekleriyle anlatılır. Sekte yapılırken dikkat edilmesi gereken', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.2.7', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Kur’an-ı Kerim tilavetinde okunuşu özel olan kelimeler tanıtılır. Konu bağlamında “imale”,', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.2.8', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Kur’an-ı Kerim okurken nerede durulacağı ve durduktan sonra okumaya tekrar nasıl baş-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.2.9', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Kur’an-ı Kerim’de bazı özel işaretlerin bulunduğu, bu işaretlerin Kur’an-ı Kerim’in düzenli', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.3.1', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Al-i İmran, Nisa, Yasin ve Nebe surelerini yüzünden okuyabilme', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.4.1', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Duha ila Hümeze surelerini anlamada Kur’an-ı Kerim meallerine başvurabilme', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.10.4.2', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Kur’an-ı Kerim’den bazı sureler ezberlemenin dinimizde özel bir yere sahip olduğu vurgula-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Öğrencilere Kur’an-ı Kerim’in gönderiliş amaçlarının neler olduğu sorulur. Kur’an-ı Kerim’in', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Hz. Peygamber Dönemi’nde Kur’an-ı Kerim öğretimi ile ilgili bilgileri', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'vit kurallarının bütüncül biçimde uygulanıp tekrar edilmesine dayalı çalışmaların önemi', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Maide, Enam, Araf ve Mülk surelerini yüzünden okuyabilme', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.11.4.1', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Öğrencilerden Bakara suresinin 153-157. ayetlerinin ve Yasin suresinin anlamlarını incele-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.11.4.2', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Bakara suresinin 153-157. ayetlerinin ve Yasin suresinin okunma ve ezberlenmesinin kül-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.12.1.1', 'ihl_meslek_dersleri', 12, 1, 'Ünite 1', 'Öğrencilere Kur’an-ı Kerim tilavetinde kullanılan hadr, tedvir ve tahkik kavramları açıkla-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.12.1.2', 'ihl_meslek_dersleri', 12, 1, 'Ünite 1', 'Kıraat ilminin tanımı ele alınır. Hz. Peygamber Dönemi’nde ortaya çıkan kıraat ilminin ge-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.12.2.1', 'ihl_meslek_dersleri', 12, 2, 'Ünite 2', 'vit kurallarının bütüncül biçimde uygulanıp tekrar edilmesine dayalı çalışmaların önemi', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.12.3.1', 'ihl_meslek_dersleri', 12, 3, 'Ünite 3', 'Fetih, Hucurat, Rahman, Vakıa, Saf ve Cuma surelerini yüzünden okuyabilme', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.12.4.1', 'ihl_meslek_dersleri', 12, 4, 'Ünite 4', 'Öğrencilerden Al-i İmran suresinin 189-194 ve Fetih suresinin 27-29. ayetlerinin anlamla-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('KKIHL.12.4.2', 'ihl_meslek_dersleri', 12, 4, 'Ünite 4', 'Al-i İmran suresinin 189-194 ve Fetih suresinin 27-29. ayetleri öğretmen tarafından eu-', '', 'Kur''an-ı Kerim', 'ihl', 'zorunlu'),
  ('MARP.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinleriyle ilgili', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinleriyle ilgili bilgileri bir araya getirebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.1.3', 'ihl_meslek_dersleri', 11, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinlerini tahlil edebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.1.4', 'ihl_meslek_dersleri', 11, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinlerini yorumlayabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.1.5', 'ihl_meslek_dersleri', 11, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinleriyle ilgili bilgi, deneyim, düşünce ve duygularını', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” metinleriyle ilgili okumaya hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.2.2', 'ihl_meslek_dersleri', 11, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” metinleriyle ilgili bilgileri bir araya getirebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.2.3', 'ihl_meslek_dersleri', 11, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” metinlerindeki dinî kavramları ayırt edebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.2.4', 'ihl_meslek_dersleri', 11, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” metinlerindeki dinî kavramları bağlamına uygun', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.2.5', 'ihl_meslek_dersleri', 11, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” metinleriyle ilgili bilgi, deneyim, düşünce ve duygularını', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Tema 3: Tema 3', '“İbadetler” metinleriyle ilgili okumaya hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.3.2', 'ihl_meslek_dersleri', 11, 3, 'Tema 3: Tema 3', '“İbadetler” metinleriyle ilgili bilgileri bir araya getirebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.3.3', 'ihl_meslek_dersleri', 11, 3, 'Tema 3: Tema 3', '“İbadetler” metinlerindeki dinî kavramları ayırt edebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.3.4', 'ihl_meslek_dersleri', 11, 3, 'Tema 3: Tema 3', '“İbadetler” metinlerindeki dinî kavramları bağlamına uygun kullanabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.3.5', 'ihl_meslek_dersleri', 11, 3, 'Tema 3: Tema 3', '“İbadetler” metinleriyle ilgili bilgi, deneyim, düşünce ve duygularını bireysel', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.4.1', 'ihl_meslek_dersleri', 11, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinleriyle ilgili okumaya hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.4.2', 'ihl_meslek_dersleri', 11, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinleriyle ilgili bilgileri bir araya getirebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.4.3', 'ihl_meslek_dersleri', 11, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinlerini anlamlandırabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.4.4', 'ihl_meslek_dersleri', 11, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinlerini tahlil edebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.4.5', 'ihl_meslek_dersleri', 11, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinlerini yorumlayabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.11.4.6', 'ihl_meslek_dersleri', 11, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinleriyle ilgili bilgi, deneyim, düşünce ve', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.1.1', 'ihl_meslek_dersleri', 12, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinleriyle ilgili okumaya hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.1.2', 'ihl_meslek_dersleri', 12, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinleriyle ilgili bilgileri bir araya getirebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.1.3', 'ihl_meslek_dersleri', 12, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinlerini tahlil edebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.1.4', 'ihl_meslek_dersleri', 12, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinlerini yorumlayabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.1.5', 'ihl_meslek_dersleri', 12, 1, 'Tema 1: Tema 1', '“İslam İnancı” metinleriyle ilgili bilgi, deneyim, düşünce ve duygularını', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.2.1', 'ihl_meslek_dersleri', 12, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” teması metinleriyle ilgili okumaya hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.2.2', 'ihl_meslek_dersleri', 12, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” teması metinleriyle ilgili bilgileri bir araya getirebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.2.3', 'ihl_meslek_dersleri', 12, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” teması metinlerini tahlil edebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.2.4', 'ihl_meslek_dersleri', 12, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” teması metinlerini yorumlayabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.2.5', 'ihl_meslek_dersleri', 12, 2, 'Tema 2: Tema 2', '“Kur’an-ı Kerim” metinleriyle ilgili bilgi, deneyim, düşünce ve duygularını', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.3.1', 'ihl_meslek_dersleri', 12, 3, 'Tema 3: Tema 3', '“İbadetler” metinleriyle ilgili okumaya hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.3.2', 'ihl_meslek_dersleri', 12, 3, 'Tema 3: Tema 3', '“İbadetler” metinleriyle ilgili bilgileri bir araya getirebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.3.3', 'ihl_meslek_dersleri', 12, 3, 'Tema 3: Tema 3', '“İbadetler” metinlerindeki dinî kavramları ayırt edebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.3.4', 'ihl_meslek_dersleri', 12, 3, 'Tema 3: Tema 3', '“İbadetler” metinlerindeki dinî kavramları bağlamına uygun kullanabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.3.5', 'ihl_meslek_dersleri', 12, 3, 'Tema 3: Tema 3', '“İbadetler” metinleriyle ilgili bilgi, deneyim, düşünce ve duygularını bireysel', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.4.1', 'ihl_meslek_dersleri', 12, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinleriyle ilgili okumaya hazırlık yapabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.4.2', 'ihl_meslek_dersleri', 12, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinleriyle ilgili bilgileri bir araya getirebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.4.3', 'ihl_meslek_dersleri', 12, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinlerini anlamlandırabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.4.4', 'ihl_meslek_dersleri', 12, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinlerini tahlil edebilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.4.5', 'ihl_meslek_dersleri', 12, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinlerini yorumlayabilme', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('MARP.12.4.6', 'ihl_meslek_dersleri', 12, 4, 'Tema 4: Tema 4', '“Hz. Muhammed (sav)” metinleriyle ilgili bilgi, deneyim, düşünce ve', '', 'Mesleki Arapça', 'ihl', 'secmeli'),
  ('SYR.10.4.1', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Üsveihasene kavramı açıklanır. Hz. Peygamber’in sosyal, siyasi, askerî alan­larda; ibadet', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.1.1', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Hz. Muhammed’in (sav) doğduğu bölgenin tarihî yapısını özetleyebilme', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.1.2', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Hz. Muhammed’in (sav) doğduğu bölgenin sosyal ve kültürel yapısı ile ilgili', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.1.3', 'ihl_meslek_dersleri', 10, 1, 'Ünite 1', 'Hz. Peygamber’in soyu ve aile büyükleri hakkında bilgi verilir. Peygamber Efendimiz’in ço­', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.2.1', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Vahiy kavramı açıklanır. İlk vahyin nazil oluşu ve Hz. Peygamber’in bu durumu nasıl karşıladığı', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.2.2', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Müşriklerin genel özellik­leri verilir. Bu özellikler ile İslam davetine tepkiler arasında ilişki', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.2.3', 'ihl_meslek_dersleri', 10, 2, 'Ünite 2', 'Müslümanların Habeşistan’a hicretleri sebep ve sonuçlarıyla birlikte ele alınır. Hicret', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.3.1', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Hicret’ten sonra Medine’de tesis edilen toplumsal yapıya dikkat çekilir. Hz. Peygamber’in Me­', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.3.2', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Müslümanlara savaş izni verilmesi sürecine değinilir. Cihat, seriyye ve gazve kavramları', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.3.3', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Hz. Peygamber tarafından gönderilen İslam’a davet mektuplarının içerikleri, muhatapları ve', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.3.4', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Veda Haccı hakkında bilgi verilir. Konu bu kapsamda fıkıh dersiyle ilişkilendirilir. Hz. Peygam­', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.3.5', 'ihl_meslek_dersleri', 10, 3, 'Ünite 3', 'Hz. Peygamber’in hastalık süreci ele alınır. Peygamber Efendimiz’in hastalık sürecinde as­', '', 'Siyer', 'ihl', 'zorunlu'),
  ('SYR.10.4.2', 'ihl_meslek_dersleri', 10, 4, 'Ünite 4', 'Örf kavramı açıklanır. Peygamber Efendimiz’e duyulan sevginin kültürümüzdeki yansıma­', '', 'Siyer', 'ihl', 'zorunlu'),
  ('TK.1.1', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Tasavvufun mahiyetini çözümleyebilme', '', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.1.2', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Tasavvufun tarihsel gelişimini özetleyebilme', '', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.2.1', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Tasavvufta eğitimle ilgili dinî kavramları bağlamına uygun kullanabilme', '', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.2.2', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Kültürümüzde etkili olan tasavvufi yorumları mukayese yapabilme', '', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.3.1', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Ahlakın tasavvufi hayattaki yerini sentezleyebilme', '', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.3.2', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Tasavvufta bilgi ve varlık ile ilgili konuları idrak edebilme', '', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.4.1', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Tasavvufun kültürümüze ve İslam medeniyetine yansımalarını müşahede', '', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.4.2', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Tasavvufun günlük hayata etkisini gözleme dayalı tahmin edebilme', '', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TDB.9.1.1', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'İnsanın kendisini, kâinatın yaratılış özelliklerini ve yaratılış amacını bilmesinin önemi vurgu­', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TDB.9.1.2', 'ihl_meslek_dersleri', 9, 1, 'Ünite 1', 'Allah (cc), insan ve kâinat ilişkisi ile ilgili akli ve naklî delilleri kullanabilme', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TDB.9.2.1', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'İmanın mahiyeti ve iman etmenin insana neler kazandırdığı açıklanır. İmanla ilgili kavram­', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TDB.9.2.2', 'ihl_meslek_dersleri', 9, 2, 'Ünite 2', 'İman esasları ayetlerden ve hadislerden yararlanılarak ele alınır. Bu süreçte melek, kitap,', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TDB.9.3.1', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', 'İbadetlerin insanın hayatındaki yeri ve önemine değinilir. Bu bağlamda ibadetlerin günlük', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TDB.9.3.2', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', 'İslam’da ibadet ve temizlik arasındaki ilişkiye yer verilir. Öğrencilerin ibadet ve temizlik', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TDB.9.3.3', 'ihl_meslek_dersleri', 9, 3, 'Ünite 3', 'İslam’da temel ibadetler olarak kabul edilen namaz, oruç, zekât, hac ve kurban ibadet­', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TDB.9.4.1', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'İslam ahlakı ile ilgili konuları özetleyebilme', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TDB.9.4.2', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'İslam ahlakına göre tutum ve davranışlara ilişkin analitik düşünebilme', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TDB.9.4.3', 'ihl_meslek_dersleri', 9, 4, 'Ünite 4', 'Kötü alışkanlıklar ve bağımlılıkların insan hayatındaki fiziksel ve ruhsal etkilerine yer verilir.', '', 'Temel Dini Bilgiler', 'ihl', 'zorunlu'),
  ('TFS.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Kur’an’ı anlamak için gerekli olan temel ilkeler (dile vâkıf olma, tarihî bilgilere hâkimiyet, bağ-', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Kur’an-ı Kerim’in indiriliş süreci kapsamında vahyin mahiyeti, geliş yolları, kayıt altına alınması', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Öğrencilerden farklı ilimlerden yararlanmanın Kur’an’ı doğru anlamadaki önemini sorgulama-', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.1.3', 'ihl_meslek_dersleri', 11, 1, 'Ünite 1', 'Öğrencilerin tefsir ilminin teşekkül sürecini, İslami ilimlerin ortaya çıkmasıyla ilgili ön öğren-', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.2.2', 'ihl_meslek_dersleri', 11, 2, 'Ünite 2', 'Tefsir ilminde kaynak, yöntem, konu, yaklaşım gibi çeşitli değişkenlere göre yapılan sı-', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Kur’an’da Allah Teala’yı tanıtan ayetlerle ilgili kısaca bilgi verilir. İhlas suresinin tefsiri ile Haşr', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.3.2', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'İsra suresinin 70, Tin suresinin 4 ve Mülk suresinin 2. ayetleri verilerek öğrencilerden insanın', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.3.3', 'ihl_meslek_dersleri', 11, 3, 'Ünite 3', 'Toplumsal hayatı düzenlemeye yönelik ayetlerdeki emir ve yasaklar hakkında kısaca bilgi', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.4.1', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Fatiha suresini tahkik edebilme', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.4.2', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Asr suresinde ele alınan konular hakkında analitik düşünebilme', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.4.3', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Maun suresi ile ilgili genel bilgiler verilerek sure tanıtılır. Maun suresinin çeşitli kaynak-', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.4.4', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Kevser suresi ile ilgili genel bilgiler verilerek sure tanıtılır. Surenin tefsiri, çeşitli tefsir kaynak-', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TFS.11.4.5', 'ihl_meslek_dersleri', 11, 4, 'Ünite 4', 'Nasr suresi ile ilgili genel bilgiler verilerek sure tanıtılır. Surenin nüzul sebebi kapsamında', '', 'Tefsir', 'ihl', 'zorunlu'),
  ('TZ.9.1.1', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Tezhip sanatının tanımı ve tarihi hakkında bilgi toplayabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.9.1.2', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Tezhip sanatında kullanılan malzemeleri kullanım amaçlarına göre çözümle-', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.9.1.3', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Temel çizimleri örneklere bakarak aslına uygun çizebilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.9.1.4', 'ihl_meslek_dersleri', 9, 1, 'Düzey I - Ünite 1', 'Renkleri özelliklerine göre sınıflandırabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.9.2.1', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Motifleri özelliklerine göre sınıflandırabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.9.2.2', 'ihl_meslek_dersleri', 9, 2, 'Düzey I - Ünite 2', 'Motif örneklerine bakarak bunları aslına uygun çizebilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.9.3.1', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Uygulama tekniklerini algılayabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.9.3.2', 'ihl_meslek_dersleri', 9, 3, 'Düzey I - Ünite 3', 'Uygulama tekniklerini kullanarak bir tezhip eseri oluşturabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.9.4.1', 'ihl_meslek_dersleri', 9, 4, 'Düzey I - Ünite 4', 'Tezhip sanatına yön veren müzehhiplerin üsluplarını karşılaştırabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.9.4.2', 'ihl_meslek_dersleri', 9, 4, 'Düzey I - Ünite 4', 'Müzehhiplere ait eserlerin çizimini (reprodüksiyon) yapabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.10.1.1', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Cetvel çekimi ve zencerek yapımını çözümleyebilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.10.1.2', 'ihl_meslek_dersleri', 10, 1, 'Düzey II - Ünite 1', 'Cetvel çekimi ve zencerek yapabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.10.2.1', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Rumi motifli kompozisyonları çözümleyebilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.10.2.2', 'ihl_meslek_dersleri', 10, 2, 'Düzey II - Ünite 2', 'Rumi motifli tezhip eseri oluşturabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.10.3.1', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Bulut motifli kompozisyonları çözümleyebilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.10.3.2', 'ihl_meslek_dersleri', 10, 3, 'Düzey II - Ünite 3', 'Bulut motifli tezhip eseri oluşturabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.10.4.1', 'ihl_meslek_dersleri', 10, 4, 'Düzey II - Ünite 4', 'Desenleri çözümleyebilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.10.4.2', 'ihl_meslek_dersleri', 10, 4, 'Düzey II - Ünite 4', 'Tezhip eseri yapabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.11.1.1', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Tarihî dönemlere göre tezhip sanatını özetleyebilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.11.1.2', 'ihl_meslek_dersleri', 11, 1, 'Düzey III - Ünite 1', 'Selçuklu, Osmanlı ve Cumhuriyet dönemlerine ait bir eserin çizimini', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.11.2.1', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Tezhip sanatının uygulama alanları hakkında bilgi toplayabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.11.2.2', 'ihl_meslek_dersleri', 11, 2, 'Düzey III - Ünite 2', 'Surebaşı çizimini (reprodüksiyon) yapabilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.11.3.1', 'ihl_meslek_dersleri', 11, 3, 'Düzey III - Ünite 3', 'Sanat eserini aslına uygun çizebilme', '', 'Tezhip', 'ihl', 'secmeli'),
  ('TZ.11.4.1', 'ihl_meslek_dersleri', 11, 4, 'Düzey III - Ünite 4', 'Tezhip eseri yapabilme', '', 'Tezhip', 'ihl', 'secmeli')
) AS v(kod, brans_slug, sinif, unite_no, unite_ad, ad, aciklama, ders, okul_tipi, ders_turu)
JOIN branslar b ON b.slug = v.brans_slug
ON CONFLICT (kod) DO UPDATE SET
  ad = EXCLUDED.ad,
  sinif = EXCLUDED.sinif,
  unite_no = EXCLUDED.unite_no,
  unite_ad = EXCLUDED.unite_ad,
  ders = EXCLUDED.ders,
  okul_tipi = EXCLUDED.okul_tipi,
  ders_turu = EXCLUDED.ders_turu;

-- Toplam: 469 kazanım