-- Migration 041: Seçmeli ders kazanımları — extracted/ JSON kaynaklı
-- 2026-05-29
-- Kaynak dosyalar: sosyoloji, takımsporları, tsvkltr, islamfelsefesi, içe,
--                  dinegitimi, islambilimtarh, temelmatematik
-- Toplam: 170 kazanım
--
-- Stats:
--   sosyoloji.json → felsefe: 20 eklendi, 1 atlandı
--   takımsporları.json → beden_egitimi: 45 eklendi, 0 atlandı
--   tsvkltr.json → ihl_meslek_dersleri: 8 eklendi, 0 atlandı
--   islamfelsefesi.json → ihl_meslek_dersleri: 11 eklendi, 0 atlandı
--   içe.json → ihl_meslek_dersleri: 10 eklendi, 1 atlandı
--   dinegitimi.json → ihl_meslek_dersleri: 10 eklendi, 1 atlandı
--   islambilimtarh.json → ihl_meslek_dersleri: 27 eklendi, 1 atlandı
--   islambilimtarh.json → tarih: 27 eklendi, 1 atlandı
--   temelmatematik.json → matematik: 12 eklendi, 6 atlandı

INSERT INTO kazanimlar (kod, brans_id, sinif, unite_no, unite_ad, ad, ders, okul_tipi, ders_turu)
VALUES
  ('SOS.11.1.1', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 1, '', 'Sosyolojinin doğuş sürecini tarihsel', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.1.2', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 1, '', 'Sosyolojik düşünme biçimini sorgulayabilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.1.3', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 1, '', 'Sosyolojide kullanılan farklı yöntemleri karşılaştırabilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.2.1', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 2, '', 'Osmanlı''dan Cumhuriyet''e modernleşmenin neden ve sonuçlarını yorumla-', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.2.2', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 2, '', 'Türkiye''de sosyolojinin doğuşu ve gelişim sürecini tarihsel bir kurgu içinde', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.2.3', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 2, '', 'Türk modernleşmesinin Türk edebiyatına yansımasını yorumlayabilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.3.2', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 3, '', 'Toplumsal yapının unsurlarını ve bu unsurlar arasındaki ilişkileri çözümleyebilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.3.3', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 3, '', 'Toplumsal tabakalaşmayı ve toplumsal hareketliliği özetleyebilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.4.1', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 4, '', 'Aile kurumunun işlevi ve yapısı ile evlilik türleri üzerine eleştirel düşünebilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.4.2', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 4, '', 'Eğitim kurumunun işlevi ve toplumsal yaşamdaki önemi ve değeri üzerine', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.4.3', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 4, '', 'Din kurumunun işlevlerini yapılandırabilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.4.4', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 4, '', 'Ekonomi kurumunun işlevi ve toplumsal yaşam açısından önemi hakkında çı-', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.4.5', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 4, '', 'Siyaset kurumunun işlevi ve önemi hakkında eleştirel düşünebilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.4.6', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 4, '', 'Toplumsal kurumların işlevlerini birbirleriyle ilişkisi içinde inceleyerek toplu-', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.5.1', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 5, '', 'İslam karşıtlığı problemi ile ilgili eleştirel düşünebilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.5.2', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 5, '', 'Küreselleşme olgusunun toplumsal etkilerini çözümleme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.11.5.3', (SELECT id FROM branslar WHERE slug = 'felsefe'), 11, 5, '', 'Yapay zekâ teknolojileri kaynaklı toplumsal sorunlar hakkında eleştirel düşü-', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.12.1.1', (SELECT id FROM branslar WHERE slug = 'felsefe'), 12, 1, '', 'Bilim ve toplum ilişkisini çözümleyebilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.12.1.2', (SELECT id FROM branslar WHERE slug = 'felsefe'), 12, 1, '', 'Bilim ve toplum ilişkisi üzerine eleştirel düşünebilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('SOS.12.2.1', (SELECT id FROM branslar WHERE slug = 'felsefe'), 12, 2, '', 'Güncel toplumsal meseleler hakkında eleştirel düşünebilme', 'Sosyoloji', 'lise', 'secmeli'),
  ('TKS.9.1.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 1, '', 'Oyun kurallarındaki değişimin basketbolun gelişimi üzerindeki etkilerini yorum-', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.1.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 1, '', 'Basketbola özgü ısınma ve soğuma hareketlerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.1.3', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 1, '', 'Basketbolda el-top uyumu becerisini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.1.4', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 1, '', 'Basketbolda stop becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.1.5', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 1, '', 'Basketbolda top sürme becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.2.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 2, '', 'Oyun kurallarındaki değişimin futbolun gelişimi üzerindeki etkilerini yorumlaya-', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.2.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 2, '', 'Futbola özgü ısınma ve soğuma hareketlerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.2.3', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 2, '', 'Futbolda topa yatkınlık becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.2.4', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 2, '', 'Futbolda top sürme becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.3.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 3, '', 'Oyun kurallarındaki değişimin hentbolun gelişimi üzerindeki etkilerini yorum-', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.3.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 3, '', 'Hentbola özgü ısınma ve soğuma hareketlerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.3.3', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 3, '', 'Hentbolda el-top uyumu becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.3.4', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 3, '', 'Hentbolda top sürme becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.3.5', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 3, '', 'Hentbolda pas becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.4.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 4, '', 'Oyun kurallarındaki değişimin voleybolun gelişimi üzerindeki etkilerini yorumla-', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.4.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 4, '', 'Voleybola özgü ısınma ve soğuma hareketlerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.4.3', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 4, '', 'Voleybolda el-top uyumu becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.9.4.4', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 9, 4, '', 'Voleybolda pas becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.10.1.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 10, 1, '', 'Basketbolda pas becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.10.1.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 10, 1, '', 'Basketbolda şut becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.10.2.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 10, 2, '', 'Futbolda top kontrol becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.10.2.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 10, 2, '', 'Futbolda topa vuruş becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.10.3.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 10, 3, '', 'Hentbolda aldatma becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.10.3.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 10, 3, '', 'Hentbolda kale atışı becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.10.4.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 10, 4, '', 'Voleybolda servis becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.10.4.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 10, 4, '', 'Voleybolda smaç becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.1.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 1, '', 'Basketbolda aldatma becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.1.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 1, '', 'Basketbolda perdeleme ve yuvarlanma becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.1.3', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 1, '', 'Basketbolda ribaunt becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.2.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 2, '', 'Futbolda aldatma becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.2.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 2, '', 'Futbolda taç atışı becerisini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.2.3', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 2, '', 'Futbolda kaleci becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.3.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 3, '', 'Hentbolda perdeleme ve yuvarlanma becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.3.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 3, '', 'Hentbolda kaleci becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.4.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 4, '', 'Voleybolda blok becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.11.4.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 11, 4, '', 'Voleybolda plonjon becerilerini sergileyebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.12.1.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 12, 1, '', 'Basketbol savunma sistemlerinin uygulanmasında eşle/grupla hareket ede-', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.12.1.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 12, 1, '', 'Basketbol hücum sistemlerinin uygulanmasında eşle/grupla hareket edebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.12.2.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 12, 2, '', 'Futbol savunma prensiplerinin uygulanmasında eşle/grupla hareket edebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.12.2.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 12, 2, '', 'Futbol hücum prensiplerinin uygulanmasında eşle/grupla hareket edebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.12.2.3', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 12, 2, '', 'Futbol oyun sistemlerinin uygulanmasında eşle/grupla hareket edebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.12.3.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 12, 3, '', 'Hentbol savunma sistemlerinin uygulanmasında eşle/grupla hareket edebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.12.3.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 12, 3, '', 'Hentbol hücum sistemlerinin uygulanmasında eşle/grupla hareket edebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.12.4.1', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 12, 4, '', 'Voleybol savunma sistemlerinin uygulanmasında eşle/grupla hareket edebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TKS.12.4.2', (SELECT id FROM branslar WHERE slug = 'beden_egitimi'), 12, 4, '', 'Voleybol hücum sistemlerinin uygulanmasında eşle/grupla hareket edebilme', 'Takım Sporları', 'lise', 'secmeli'),
  ('TK.1.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'Tasavvufun mahiyetini TK.1.1.', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.1.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'Tasavvufun tarihsel gelişimini özetleyebilme', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.2.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Tasavvufta eğitimle ilgili dinî kavramları bağlamına uygun kullanabilme', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.2.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Kültürümüzde etkili olan tasavvufi yorumları mukayese yapabilme', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.3.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Ahlakın tasavvufi hayattaki yerini sentezleyebilme', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.3.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Tasavvufta bilgi ve varlık ile ilgili konuları idrak edebilme', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.4.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Tasavvufun kültürümüze ve İslam medeniyetine yansımalarını müşahede', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('TK.4.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Tasavvufun günlük hayata etkisini gözleme dayalı tahmin edebilme', 'Tasavvuf Kültürü', 'ihl', 'secmeli'),
  ('İF.1.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslam felsefesiyle ilgili yapılan tanımlar', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.1.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslam felsefesinin gelişimine kaynaklık eden faktörleri özetleyebilme', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.1.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslam felsefesinin geliştiği ilim ve kültür havzalarıyla ilgili konuları müşahede ede-', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.1.4', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslam felsefesinin diğer disiplinlerle ilişkisini çözümleyebilme', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.2.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Varlık, bilgi ve ahlak konularını anlayabilme', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.3.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Meşşai felsefeyle ilgili konuları müşahede edebilme', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.3.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'İşrak felsefesi hakkında bilgi toplayabilme', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.4.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Endülüs''te yapılan İslam felsefesi çalışmalarını müşahede edebilme', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.4.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Osmanlı Dönemi İslam felsefesinin genel karakterini anlayabilme', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.4.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Yakın dönem İslam felsefesi çalışmalarını genelleyebilme', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İF.4.4', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'İslam felsefesinin Batı''ya etkisi konusunda eleştirel düşünebilme', 'İslam Felsefesi', 'ihl', 'secmeli'),
  ('İÇE.1.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslam''ın çocuğa bakışıyla ilgili', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.1.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslam''da çocuk eğitiminde ailenin önemini müşahede edebilme', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.1.4', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'Gelişim alanlarını özetleyebilme', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.2.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Çocukta inanç gelişim özelliklerini yorumlayabilme', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.2.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Çocuğun inanç gelişimini etkileyen faktörleri müşahede edebilme', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.2.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Çocuğun gelişimine göre inanç esaslarının öğretimini tatbik edebilme', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.3.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Çocuğun gelişim özelliklerine göre ibadet algısını müşahede edebilme', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.3.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Çocuğun gelişimine göre ibadet eğitimini tatbik edebilme', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.4.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Çocukta ahlak gelişim dönemlerini müşahede edebilme.', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('İÇE.4.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'İslam''daki ahlaki değerleri yaş gruplarının özelliklerine göre yorumlayabilme.', 'İslam''da Çocuk Eğitimi', 'ihl', 'secmeli'),
  ('DE.1.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'Din eğitimi ile ilgili temel kavramları', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.1.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'Din eğitimi biliminin önemi ve gerekliliği konusunda analitik düşünebilme', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.2.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Gelişim dönemlerine göre din eğitimi uygulamalarını sınıflandırabilme', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.2.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Gelişim dönemlerinde dinî anlayışı etkileyen unsurları özetleyebilme', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.2.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Gençlik dönemi kimlik inşasında dinin etkisini müşahede edebilme', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.3.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Değer temelli ahlak eğitiminin önemini anlayabilme', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.3.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Çevresel unsurların ahlak ve değer eğitimindeki rolünü yorumlayabilme', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.3.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Ahlak ve değer eğitimi yaklaşımlarını temel alan din eğitimi uygulamaları hakkında', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.4.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Türkiye''de yürütülen örgün din eğitimi uygulamalarını yapılandırabilme', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('DE.4.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Türkiye''de yürütülen yaygın din eğitimi örneklerini mesleki olarak uygulayabilme', 'Din Eğitimi', 'ihl', 'secmeli'),
  ('İBT.1.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslam biliminin temel kavramları ve ge-', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslam dünyasında bilimin gelişmesinde etkili olan unsurları yorumlayabilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.4', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'Şehirlerin bilim, sanat ve irfana etkisi ile ilgili bilgi toplayabilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.5', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslami ilimlerin oluşumunu kaynağından inceleyebilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.6', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'Teoriden pratiğe İslam dünyasında bilime yönelik ilk çalışma alanları ile ilgili çı-', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.7', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'İslam dünyasında tercüme faaliyetlerinin nedenlerini sorgulayabilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.8', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 1, '', 'Bilim alanlarını yeniden sınıflandırabilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'Yeni siyasi, iktisadi, kültürel yapılanma ve ilim merkezlerinin oluşumu ile ilgili', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'İslam dünyasında ilk medreselerin kuruluş nedenlerini sorgulayabilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'İslam bilim tarihinde gözlem ve deneye yönelimi tarihsel bağlamsallaştırma ile', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.4', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'İslam dünyasında gök bilimi, matematik, fen, sağlık bilimleri ve sosyal bilimler', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.2.5', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 2, '', 'İslam dünyasında yapılan teknik ürünlerle ilgili analojik akıl yürütebilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.3.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Endülüs Bilim Havzası''nda yapılan bilimsel çalışmalar ile ilgili kaynaklardan bilgi', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.3.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'Harita üzerinden İslam biliminin Avrupa''ya geçiş yolları ile ilgili çıkarım yapabilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.3.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 3, '', 'İslam biliminin Avrupa''da yeni bir medeniyetin doğuşuna etkisini yorumlayabilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.4.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Türkistan Bilim Havzası''ndaki bilimsel çalışmaları tarihsel bağlamda değerlen-', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.4.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Haçlı saldırılarının bilimin Batı''ya geçişindeki etkilerini yapılandırabilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.4.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 4, '', 'Büyük Selçuklular, Birinci Beylikler ve Türkiye Selçukluları Dönemi bilimsel ça-', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 5, '', 'Erken Dönem Osmanlı bilim anlayışının oluşumunu ve Türkçenin bilim dili hâline', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 5, '', 'İstanbul''un bilim merkezi hâline gelme sürecindeki unsurları yapılandırabilme', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.3', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 5, '', 'Takıyyüddin Rasıd ve İstanbul Rasathanesinin açılışı ve yapılan çalışmalar ile il-', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.4', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 5, '', 'Osmanlı Devleti''nde coğrafya, haritacılık, kartografya ve tıp alanında yapılan ça-', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.5', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 5, '', 'Osmanlı Devleti''nde yeni eğitim kurumlarının açılış nedenlerini ve yeni bilimsel', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.6', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 5, '', 'XVIII-XIX. yüzyılda eğitim ve bilim alanında faaliyet gösteren bilim insanlarının', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.5.7', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 5, '', 'Osmanlı Devleti''nde modern yapılanmanın ve Rasathâne-i Âmire''de yapılan ça-', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.6.1', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 6, '', 'Cumhuriyet Dönemi bilim politikalarını ve yeni kurulan bilim kurumlarının çalış-', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.6.2', (SELECT id FROM branslar WHERE slug = 'ihl_meslek_dersleri'), 11, 6, '', 'Cumhuriyet Dönemi bilim insanlarının çalışmaları hakkında kaynaklardan bilgi', 'İslam Bilim Tarihi', 'ihl', 'secmeli'),
  ('İBT.1.1_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 1, '', 'İslam biliminin temel kavramları ve ge-', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.1.3_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 1, '', 'İslam dünyasında bilimin gelişmesinde etkili olan unsurları yorumlayabilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.1.4_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 1, '', 'Şehirlerin bilim, sanat ve irfana etkisi ile ilgili bilgi toplayabilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.1.5_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 1, '', 'İslami ilimlerin oluşumunu kaynağından inceleyebilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.1.6_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 1, '', 'Teoriden pratiğe İslam dünyasında bilime yönelik ilk çalışma alanları ile ilgili çı-', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.1.7_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 1, '', 'İslam dünyasında tercüme faaliyetlerinin nedenlerini sorgulayabilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.1.8_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 1, '', 'Bilim alanlarını yeniden sınıflandırabilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.2.1_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 2, '', 'Yeni siyasi, iktisadi, kültürel yapılanma ve ilim merkezlerinin oluşumu ile ilgili', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.2.2_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 2, '', 'İslam dünyasında ilk medreselerin kuruluş nedenlerini sorgulayabilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.2.3_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 2, '', 'İslam bilim tarihinde gözlem ve deneye yönelimi tarihsel bağlamsallaştırma ile', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.2.4_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 2, '', 'İslam dünyasında gök bilimi, matematik, fen, sağlık bilimleri ve sosyal bilimler', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.2.5_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 2, '', 'İslam dünyasında yapılan teknik ürünlerle ilgili analojik akıl yürütebilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.3.1_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 3, '', 'Endülüs Bilim Havzası''nda yapılan bilimsel çalışmalar ile ilgili kaynaklardan bilgi', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.3.2_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 3, '', 'Harita üzerinden İslam biliminin Avrupa''ya geçiş yolları ile ilgili çıkarım yapabilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.3.3_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 3, '', 'İslam biliminin Avrupa''da yeni bir medeniyetin doğuşuna etkisini yorumlayabilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.4.1_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 4, '', 'Türkistan Bilim Havzası''ndaki bilimsel çalışmaları tarihsel bağlamda değerlen-', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.4.2_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 4, '', 'Haçlı saldırılarının bilimin Batı''ya geçişindeki etkilerini yapılandırabilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.4.3_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 4, '', 'Büyük Selçuklular, Birinci Beylikler ve Türkiye Selçukluları Dönemi bilimsel ça-', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.5.1_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 5, '', 'Erken Dönem Osmanlı bilim anlayışının oluşumunu ve Türkçenin bilim dili hâline', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.5.2_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 5, '', 'İstanbul''un bilim merkezi hâline gelme sürecindeki unsurları yapılandırabilme', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.5.3_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 5, '', 'Takıyyüddin Rasıd ve İstanbul Rasathanesinin açılışı ve yapılan çalışmalar ile il-', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.5.4_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 5, '', 'Osmanlı Devleti''nde coğrafya, haritacılık, kartografya ve tıp alanında yapılan ça-', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.5.5_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 5, '', 'Osmanlı Devleti''nde yeni eğitim kurumlarının açılış nedenlerini ve yeni bilimsel', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.5.6_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 5, '', 'XVIII-XIX. yüzyılda eğitim ve bilim alanında faaliyet gösteren bilim insanlarının', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.5.7_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 5, '', 'Osmanlı Devleti''nde modern yapılanmanın ve Rasathâne-i Âmire''de yapılan ça-', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.6.1_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 6, '', 'Cumhuriyet Dönemi bilim politikalarını ve yeni kurulan bilim kurumlarının çalış-', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('İBT.6.2_TRH', (SELECT id FROM branslar WHERE slug = 'tarih'), 11, 6, '', 'Cumhuriyet Dönemi bilim insanlarının çalışmaları hakkında kaynaklardan bilgi', 'İslam Bilim Tarihi', 'lise', 'secmeli'),
  ('MAT.T.11.1.1_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 11, 1, '', 'Niceliklerin doğru orantılı değişimlerini gerçek sayılarda tanımlı f(x) = ax', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.T.11.1.2_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 11, 1, '', 'Niceliklerin ters orantılı değişimlerini - {0} da tanımlı g(x) = fonksi-', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.T.11.1.3_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 11, 1, '', 'Gerçek sayılarda tanımlı f(x) = ax veya - {0} da tanımlı g(x) = fonk-', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.11.2.1_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 11, 2, '', 'Üçgenlerde açı, benzerlik ve alan özelliklerinden yola çıkarak dörtgenlerin', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.11.2.2_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 11, 2, '', 'Çokgenlerin kenar, açı ve köşegen özelliklerine dair çıkarım yapabilme', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.T.11.3.1_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 11, 3, '', 'İki nicel değişkenli veri ile çalışabilme ve iki nicel değişken arasındaki ilişkili-', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.T.12.1.1_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 12, 1, '', 'Aritmetik ve geometrik dizilerin özelliklerine ilişkin muhakeme yapabilme', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.T.12.1.2_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 12, 1, '', 'Gerçek sayılarda tanımlı fonksiyonlar ile gerçek sayı dizilerini karşılaştıra-', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.T.12.1.3_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 12, 1, '', 'Aritmetik ve geometrik diziler ile ifade edilebilen problemleri çözebilme', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.T.12.2.1_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 12, 2, '', 'Çemberle ilişkili elemanları (kesen, kiriş, teğet, çap, yay) çözümleyebilme', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.T.12.2.2_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 12, 2, '', 'Çemberin açı, kiriş, teğet özellikleri ile ilgili çıkarım yapabilme', 'Temel Matematik', 'lise', 'secmeli'),
  ('MAT.T.12.3.1_TM', (SELECT id FROM branslar WHERE slug = 'matematik'), 12, 3, '', 'Toplumsal veya bilimsel durumlara ilişkin hazır veri ile çalışabilme ve hazır', 'Temel Matematik', 'lise', 'secmeli')
ON CONFLICT (kod) DO UPDATE SET
  ad        = EXCLUDED.ad,
  ders      = EXCLUDED.ders,
  okul_tipi = EXCLUDED.okul_tipi,
  ders_turu = EXCLUDED.ders_turu;
