-- Migration 020: Türkçe kazanımlarını geri yükle
--
-- Migration 008'deki DELETE FROM kazanimlar + migration 018'deki temizlik
-- sonucunda Türkçe branşı tamamen boşaldı. Bu migration migration 004'teki
-- doğru ünite yapısına sahip 118 Türkçe kazanımı geri yükler.
-- Sınıflar 3-4: ilkokul (Sınıf Öğretmenliği kapsamında)
-- Sınıflar 5-8: ortaokul (Türkçe branşı)

INSERT INTO kazanimlar (kod, brans_id, sinif, unite_no, unite_ad, ad, aciklama, ders, okul_tipi)
SELECT v.kod, b.id, v.sinif::integer, v.unite_no::integer, v.unite_ad, v.ad, v.aciklama, v.ders, v.okul_tipi
FROM (VALUES
  ('TK.3.1.1', 'Türkçe', 3, 1, 'Okuma Becerileri', 'Akıcı okuma', 'Metni doğru, akıcı ve anlamlı okur. Noktalama işaretlerine dikkat ederek okur.', 'Türkçe', 'ilkokul'),
  ('TK.3.1.2', 'Türkçe', 3, 1, 'Okuma Becerileri', 'Anlayarak okuma', 'Okuduğu metni kendi cümleleriyle anlatır. Ana ve yardımcı düşünceyi belirler.', 'Türkçe', 'ilkokul'),
  ('TK.3.2.1', 'Türkçe', 3, 2, 'Dinleme ve Konuşma', 'Dinleme stratejileri', 'Dinlediği metni özetler. Soruları doğru yanıtlar.', 'Türkçe', 'ilkokul'),
  ('TK.3.2.2', 'Türkçe', 3, 2, 'Dinleme ve Konuşma', 'Konuşma becerileri', 'Konuşurken ses tonunu ve vurguyu doğru kullanır. Sözlü açıklama yapar.', 'Türkçe', 'ilkokul'),
  ('TK.3.3.1', 'Türkçe', 3, 3, 'Yazma', 'Anlatı yazımı', 'Giriş-gelişme-sonuç bölümlerini içeren kısa bir hikâye yazar.', 'Türkçe', 'ilkokul'),
  ('TK.3.3.2', 'Türkçe', 3, 3, 'Yazma', 'Yazım kuralları', 'Büyük harfleri, noktalama işaretlerini ve imla kurallarını doğru kullanır.', 'Türkçe', 'ilkokul'),
  ('TK.3.4.1', 'Türkçe', 3, 4, 'Dil Bilgisi', 'İsimler ve zamirler', 'İsimleri türlerine göre sınıflandırır. Kişi zamirlerini tanımlar ve kullanır.', 'Türkçe', 'ilkokul'),
  ('TK.3.4.2', 'Türkçe', 3, 4, 'Dil Bilgisi', 'Fiiller ve zaman', 'Fiillerin geniş, geçmiş ve gelecek zaman çekimlerini yapar.', 'Türkçe', 'ilkokul'),
  ('TK.3.4.3', 'Türkçe', 3, 4, 'Dil Bilgisi', 'Sıfatlar', 'Niteleme ve belirtme sıfatlarını örneklerle açıklar.', 'Türkçe', 'ilkokul'),
  ('TK.3.5.1', 'Türkçe', 3, 5, 'Sözcük Bilgisi', 'Eş anlamlı ve zıt anlamlı sözcükler', 'Eş anlamlı ve zıt anlamlı sözcükleri bağlamdan bulur.', 'Türkçe', 'ilkokul'),
  ('TK.3.5.2', 'Türkçe', 3, 5, 'Sözcük Bilgisi', 'Çok anlamlı sözcükler', 'Çok anlamlı sözcükleri cümle içinde anlamlandırır.', 'Türkçe', 'ilkokul'),
  ('TK.3.6.1', 'Türkçe', 3, 6, 'Metin Türleri', 'Şiir', 'Şiiri sesli ve doğru okur; konusunu belirler.', 'Türkçe', 'ilkokul'),
  ('TK.3.6.2', 'Türkçe', 3, 6, 'Metin Türleri', 'Masal', 'Masalın özelliklerini açıklar; kahramanları ve olayları anlatır.', 'Türkçe', 'ilkokul'),
  ('TK.4.1.1', 'Türkçe', 4, 1, 'Okuma Becerileri', 'Okuduğunu anlama ve sorgulama', 'Okuduğu metindeki ana ve yardımcı düşünceleri belirler. Metinden çıkarım yapar; sorular sorar.', 'Türkçe', 'ilkokul'),
  ('TK.4.1.2', 'Türkçe', 4, 1, 'Okuma Becerileri', 'Bilgilendirici metin okuma', 'Bilgilendirici metinlerdeki anahtar kavramları belirler. Metin yapısını analiz eder.', 'Türkçe', 'ilkokul'),
  ('TK.4.2.1', 'Türkçe', 4, 2, 'Dinleme ve Konuşma', 'Eleştirel dinleme', 'Dinlediği konuşmayı değerlendirerek neden-sonuç ilişkisi kurar.', 'Türkçe', 'ilkokul'),
  ('TK.4.2.2', 'Türkçe', 4, 2, 'Dinleme ve Konuşma', 'Planlı konuşma', 'Bir konuyu planlayarak, belli bir sıra içinde sunar.', 'Türkçe', 'ilkokul'),
  ('TK.4.3.1', 'Türkçe', 4, 3, 'Yazma', 'Bilgilendirici yazı', 'Bir konuyu açıklayan paragraf yazar; başlık belirler.', 'Türkçe', 'ilkokul'),
  ('TK.4.3.2', 'Türkçe', 4, 3, 'Yazma', 'Hikâye yazımı', 'Kuruluş, gelişme ve çözüm bölümlerini içeren hikâye yazar.', 'Türkçe', 'ilkokul'),
  ('TK.4.3.3', 'Türkçe', 4, 3, 'Yazma', 'İmla ve noktalama', 'Yazım kurallarını ve noktalama işaretlerini doğru kullanır.', 'Türkçe', 'ilkokul'),
  ('TK.4.4.1', 'Türkçe', 4, 4, 'Dil Bilgisi', 'Sözcük türleri', 'İsim, sıfat, zarf, zamir ve fiil türlerini tanımlar; örnekler verir.', 'Türkçe', 'ilkokul'),
  ('TK.4.4.2', 'Türkçe', 4, 4, 'Dil Bilgisi', 'Cümle ögeleri', 'Cümlenin öznesi ve yüklemini belirler.', 'Türkçe', 'ilkokul'),
  ('TK.4.4.3', 'Türkçe', 4, 4, 'Dil Bilgisi', 'Fiilimsi: isim-fiil', 'İsim-fiil kavramını tanımlar; cümlelerde kullanır.', 'Türkçe', 'ilkokul'),
  ('TK.4.5.1', 'Türkçe', 4, 5, 'Sözcük Bilgisi', 'Sözcüklerin yapısı: kök ve ek', 'Sözcüklerin kök ve eklerini ayırt eder. Yapım ve çekim eklerini tanır.', 'Türkçe', 'ilkokul'),
  ('TK.4.5.2', 'Türkçe', 4, 5, 'Sözcük Bilgisi', 'Mecaz ve deyimler', 'Basit deyimlerin anlamlarını bağlamdan çıkarır.', 'Türkçe', 'ilkokul'),
  ('TK.4.6.1', 'Türkçe', 4, 6, 'Metin Türleri', 'Anı ve gezi yazısı', 'Anı ve gezi yazısının özelliklerini açıklar; örnek metinler okur.', 'Türkçe', 'ilkokul'),
  ('TK.4.6.2', 'Türkçe', 4, 6, 'Metin Türleri', 'Mektup', 'Mektubun biçimsel özelliklerini tanır; kısa bir mektup yazar.', 'Türkçe', 'ilkokul'),
  ('T.5.1.1', 'Türkçe', 5, 1, 'Duygu ve Düşüncelerim', 'Metni türüne göre anlama stratejileri geliştirme', 'Okuma öncesi, sırası ve sonrasında anlama stratejileri kullanır; metin türünü belirler.', 'Türkçe', 'ortaokul'),
  ('T.5.1.2', 'Türkçe', 5, 1, 'Duygu ve Düşüncelerim', 'Ana fikri ve yardımcı fikirleri belirleme', 'Metnin ana fikrini ve onu destekleyen yardımcı fikirleri belirler.', 'Türkçe', 'ortaokul'),
  ('T.5.2.1', 'Türkçe', 5, 1, 'Duygu ve Düşüncelerim', 'Sözcük servetini geliştirme', 'Bağlamdan anlam çıkarır; sözlük kullanır; yeni sözcükleri kullanır.', 'Türkçe', 'ortaokul'),
  ('T.5.3.1', 'Türkçe', 5, 1, 'Duygu ve Düşüncelerim', 'Yazılı anlatımda planlama ve taslak oluşturma', 'Yazı yazmadan önce plan yapar; taslak oluşturur; giriş-gelişme-sonuç düzenler.', 'Türkçe', 'ortaokul'),
  ('T.5.1.3', 'Türkçe', 5, 2, 'Milli Kültürümüz', 'Sebep-sonuç ilişkilerini kavrama', 'Metindeki olayların neden-sonuç ilişkilerini belirler ve açıklar.', 'Türkçe', 'ortaokul'),
  ('T.5.4.1', 'Türkçe', 5, 2, 'Milli Kültürümüz', 'Konuşma tekniklerine uygun konuşma', 'Konuşmasını planlar; konuya uygun sözcükler seçer; ses tonunu ayarlar.', 'Türkçe', 'ortaokul'),
  ('T.5.5.1', 'Türkçe', 5, 2, 'Milli Kültürümüz', 'Dinleme/izleme stratejileri', 'Dinlerken not alır; konuşmacının amacını belirler; bilgi-yorum ayrımı yapar.', 'Türkçe', 'ortaokul'),
  ('T.5.1.4', 'Türkçe', 5, 3, 'Doğa Sevgisi', 'Şiir okuma ve anlama', 'Şiiri uygun vurgu ve tonlamayla okur; şiirin temasını açıklar.', 'Türkçe', 'ortaokul'),
  ('T.5.6.1', 'Türkçe', 5, 3, 'Doğa Sevgisi', 'Yapım ekleri: sözcük türetme', 'İsim ve fiil yapım eklerini tanır; yeni sözcükler türetir.', 'Türkçe', 'ortaokul'),
  ('T.5.3.2', 'Türkçe', 5, 3, 'Doğa Sevgisi', 'Betimleyici ve öyküleyici metin yazma', 'Betimleyici ve öyküleyici metin yazar; anlatım türlerine uygun dil kullanır.', 'Türkçe', 'ortaokul'),
  ('T.5.1.5', 'Türkçe', 5, 4, 'Medya Okuryazarlığı', 'Bilgi metinlerini anlama ve değerlendirme', 'Bilgi metinlerindeki gerçek ve yorum cümlelerini ayırt eder.', 'Türkçe', 'ortaokul'),
  ('T.5.5.2', 'Türkçe', 5, 4, 'Medya Okuryazarlığı', 'Haber ve medya metinlerini değerlendirme', 'Haber metinlerini eleştirel gözle inceler; güvenilirliğini sorgular.', 'Türkçe', 'ortaokul'),
  ('T.5.6.2', 'Türkçe', 5, 4, 'Medya Okuryazarlığı', 'Sözcük türleri: isim ve sıfat', 'İsimleri ve sıfatları kavramsal olarak ayırt eder; örnekler verir.', 'Türkçe', 'ortaokul'),
  ('T.5.1.6', 'Türkçe', 5, 5, 'Spor ve Sağlık', 'Karşılaştırmalı okuma', 'Aynı konudaki farklı metinleri karşılaştırır; ortak ve farklı yönleri belirler.', 'Türkçe', 'ortaokul'),
  ('T.5.3.3', 'Türkçe', 5, 5, 'Spor ve Sağlık', 'Kısa gazete/dergi haberi yazma', 'Gazete haberi planlar ve yazar; başlık, spot ve gövde düzenler.', 'Türkçe', 'ortaokul'),
  ('T.5.6.3', 'Türkçe', 5, 5, 'Spor ve Sağlık', 'Sözcük türleri: zamir ve zarf', 'Zamir ve zarfları tanır; cümle içindeki görevlerini belirler.', 'Türkçe', 'ortaokul'),
  ('T.5.1.7', 'Türkçe', 5, 6, 'Çevre ve Teknoloji', 'Metin içi ve metin dışı bağlantı kurma', 'Okuduğu metni daha önce okuduklarıyla ve gerçek yaşamıyla ilişkilendirir.', 'Türkçe', 'ortaokul'),
  ('T.5.4.2', 'Türkçe', 5, 6, 'Çevre ve Teknoloji', 'Tartışma ve fikir alışverişi', 'Görüşünü destekleyen argümanlar sunar; karşı görüşlere saygılı yanıt verir.', 'Türkçe', 'ortaokul'),
  ('T.5.6.4', 'Türkçe', 5, 6, 'Çevre ve Teknoloji', 'Fiil çekimi: haber kipi', 'Haber kipinin zaman eklerini tanır; fiilleri zamanlarına göre çeker.', 'Türkçe', 'ortaokul'),
  ('T.5.1.8', 'Türkçe', 5, 7, 'Üretim ve Tüketim', 'Metin yapısını çözümleme', 'Metnin giriş, gelişme ve sonuç bölümlerini belirler; paragrafları inceler.', 'Türkçe', 'ortaokul'),
  ('T.5.3.4', 'Türkçe', 5, 7, 'Üretim ve Tüketim', 'İkna edici metin yazma', 'Okuyucuyu etkilemek için argüman geliştirir; ikna edici bir metin yazar.', 'Türkçe', 'ortaokul'),
  ('T.5.6.5', 'Türkçe', 5, 7, 'Üretim ve Tüketim', 'Cümle türleri ve ögeleri', 'Yüklem, özne, nesne ve tümleçleri cümle içinde tanımlar.', 'Türkçe', 'ortaokul'),
  ('T.5.1.9', 'Türkçe', 5, 8, 'Birey ve Toplum', 'Hikâye ve roman anlama', 'Hikâye unsurlarını (olay, kişi, yer, zaman) belirler; karakterleri karşılaştırır.', 'Türkçe', 'ortaokul'),
  ('T.5.5.3', 'Türkçe', 5, 8, 'Birey ve Toplum', 'Görsel okuma ve sözlü anlatım', 'Görsel metinleri yorumlar; sözlü anlatımda beden dilini kullanır.', 'Türkçe', 'ortaokul'),
  ('T.5.6.6', 'Türkçe', 5, 8, 'Birey ve Toplum', 'Noktalama işaretleri ve yazım kuralları', 'Noktalama işaretlerini doğru kullanır; yazım kurallarını uygular.', 'Türkçe', 'ortaokul'),
  ('T.6.1.1', 'Türkçe', 6, 1, 'Erdemler', 'Farklı metin türlerini anlama ve karşılaştırma', 'Bilgilendirici ve edebi metin türleri arasındaki farkları belirler.', 'Türkçe', 'ortaokul'),
  ('T.6.1.2', 'Türkçe', 6, 1, 'Erdemler', 'Metnin temasını ve iletisini belirleme', 'Okuduğu metnin temasını ve yazarın iletisini belirler; açıklar.', 'Türkçe', 'ortaokul'),
  ('T.6.2.1', 'Türkçe', 6, 1, 'Erdemler', 'Sözcük anlamı ve bağlam', 'Bağlamdan sözcük anlamını çıkarır; sözcüklerin mecaz ve gerçek anlamlarını ayırt eder.', 'Türkçe', 'ortaokul'),
  ('T.6.3.1', 'Türkçe', 6, 2, 'Bilinç ve Sorumluluk', 'Açıklayıcı metin yazma', 'Açıklayıcı metin yazar; giriş-gelişme-sonuç yapısına uyar.', 'Türkçe', 'ortaokul'),
  ('T.6.6.1', 'Türkçe', 6, 2, 'Bilinç ve Sorumluluk', 'İsim: tanımı ve çeşitleri', 'İsim çeşitlerini (özel-cins, soyut-somut) tanımlar ve örnekler verir.', 'Türkçe', 'ortaokul'),
  ('T.6.6.2', 'Türkçe', 6, 2, 'Bilinç ve Sorumluluk', 'İsim hal ekleri', 'İsimlerin hal eklerini tanır; cümle içindeki işlevlerini açıklar.', 'Türkçe', 'ortaokul'),
  ('T.6.1.3', 'Türkçe', 6, 3, 'İletişim', 'Eleştirel okuma: kaynak değerlendirme', 'Metindeki bilgilerin güvenilirliğini sorgular; kaynakları değerlendirir.', 'Türkçe', 'ortaokul'),
  ('T.6.4.1', 'Türkçe', 6, 3, 'İletişim', 'Bilgi sunumu: hazırlıklı konuşma', 'Araştırdığı konuyu görsel destek kullanarak sunar.', 'Türkçe', 'ortaokul'),
  ('T.6.6.3', 'Türkçe', 6, 3, 'İletişim', 'Sıfatlar ve çeşitleri', 'Niteleme ve belirtme sıfatlarını tanır; derecelendirme ve pekiştirme kullanır.', 'Türkçe', 'ortaokul'),
  ('T.6.1.4', 'Türkçe', 6, 4, 'Doğa ve Evren', 'Bilim ve doğa metinlerini anlama', 'Bilimsel metinlerdeki teknik terimleri anlar; içeriği özetler.', 'Türkçe', 'ortaokul'),
  ('T.6.3.2', 'Türkçe', 6, 4, 'Doğa ve Evren', 'Deneme yazma', 'Deneme türünün özelliklerini bilir; kısa bir deneme yazar.', 'Türkçe', 'ortaokul'),
  ('T.6.6.4', 'Türkçe', 6, 4, 'Doğa ve Evren', 'Zamirler ve çeşitleri', 'Kişi, işaret ve soru zamirlerini tanır; cümle içinde kullanır.', 'Türkçe', 'ortaokul'),
  ('T.6.1.5', 'Türkçe', 6, 5, 'Sanat ve Estetik', 'Şiir: dil özellikleri ve imgeler', 'Şiirdeki imge ve mecazları belirler; şiirin anlam katmanlarını çözümler.', 'Türkçe', 'ortaokul'),
  ('T.6.3.3', 'Türkçe', 6, 5, 'Sanat ve Estetik', 'Yaratıcı yazarlık: hikâye yazmaya giriş', 'Kısa bir hikâye yazar; olay örgüsü, kişi ve mekânı belirler.', 'Türkçe', 'ortaokul'),
  ('T.6.6.5', 'Türkçe', 6, 5, 'Sanat ve Estetik', 'Zarflar ve çeşitleri', 'Zaman, yer, durum, miktar zarflarını tanır ve kullanır.', 'Türkçe', 'ortaokul'),
  ('T.6.1.6', 'Türkçe', 6, 6, 'Tarih ve Miras', 'Tarihsel metin okuma', 'Tarihsel metinleri dönemin bağlamında okur; olayları sıralar.', 'Türkçe', 'ortaokul'),
  ('T.6.5.1', 'Türkçe', 6, 6, 'Tarih ve Miras', 'Dinleme: not alma ve özetleme', 'Dinlerken önemli bilgileri not alır; dinlediğini özetler.', 'Türkçe', 'ortaokul'),
  ('T.6.6.6', 'Türkçe', 6, 6, 'Tarih ve Miras', 'Edatlar, bağlaçlar, ünlemler', 'Sözcük türlerini tamamlar; edat, bağlaç ve ünlemlerin işlevlerini açıklar.', 'Türkçe', 'ortaokul'),
  ('T.6.1.7', 'Türkçe', 6, 7, 'Girişimcilik', 'Metin yapılarını karşılaştırma', 'Farklı metin yapılarını (neden-sonuç, karşılaştırma, sorun-çözüm) tanımlar.', 'Türkçe', 'ortaokul'),
  ('T.6.3.4', 'Türkçe', 6, 7, 'Girişimcilik', 'İkna edici metin ve dilekçe yazma', 'Resmi dilekçe yazar; ikna edici metinde argüman geliştirme tekniklerini uygular.', 'Türkçe', 'ortaokul'),
  ('T.6.6.7', 'Türkçe', 6, 7, 'Girişimcilik', 'Cümle ögelerinin tekrarı', 'Temel cümle ögelerini (özne, yüklem, nesne, tümleçler) tekrar eder ve pekiştirir.', 'Türkçe', 'ortaokul'),
  ('T.6.1.8', 'Türkçe', 6, 8, 'Değerlerimiz', 'Öykü anlama: karakter analizi', 'Hikâye karakterlerinin özelliklerini ve değişimlerini analiz eder.', 'Türkçe', 'ortaokul'),
  ('T.6.4.2', 'Türkçe', 6, 8, 'Değerlerimiz', 'Panel ve tartışma', 'Panel tartışmalarına etkin katılır; görüşünü geliştirir ve savunur.', 'Türkçe', 'ortaokul'),
  ('T.6.6.8', 'Türkçe', 6, 8, 'Değerlerimiz', 'Fiil çekimi: dilek-koşul ve istek kipi', 'Dilek-koşul ve istek kiplerini tanır; doğru çekimler yapar.', 'Türkçe', 'ortaokul'),
  ('T.7.1.1', 'Türkçe', 7, 1, 'Eğitim', 'Çıkarım yaparak okuma', 'Metindeki açık ve örtük anlamları belirler; çıkarım yapar.', 'Türkçe', 'ortaokul'),
  ('T.7.1.2', 'Türkçe', 7, 1, 'Eğitim', 'Bilgi metin yapısını çözümleme', 'Bilgi metinindeki tanım, sınıflama, karşılaştırma ve açıklama tekniklerini belirler.', 'Türkçe', 'ortaokul'),
  ('T.7.6.1', 'Türkçe', 7, 1, 'Eğitim', 'Sözcük türleri: fiil kavramı ve türleri', 'Fiil türlerini (kılış, oluş, durum fiilleri) tanır; örnekler verir.', 'Türkçe', 'ortaokul'),
  ('T.7.1.3', 'Türkçe', 7, 2, 'Atatürk', 'Biyografi ve otobiyografi anlama', 'Biyografi ve otobiyografi türlerinin özelliklerini açıklar; metin inceler.', 'Türkçe', 'ortaokul'),
  ('T.7.3.1', 'Türkçe', 7, 2, 'Atatürk', 'Biyografi/röportaj yazma', 'Kısa biyografi veya röportaj yazar; yazı türünün kurallarına uyar.', 'Türkçe', 'ortaokul'),
  ('T.7.6.2', 'Türkçe', 7, 2, 'Atatürk', 'Fiil çekimi: geniş zaman ve şimdiki zaman', 'Geniş ve şimdiki zaman çekimlerini doğru kullanır; anlam farkını açıklar.', 'Türkçe', 'ortaokul'),
  ('T.7.1.4', 'Türkçe', 7, 3, 'Sağlık', 'Sağlık konulu metinleri anlama ve değerlendirme', 'Sağlık konularındaki metinlerdeki bilimsel bilgileri değerlendirir.', 'Türkçe', 'ortaokul'),
  ('T.7.4.1', 'Türkçe', 7, 3, 'Sağlık', 'Etkili sunum hazırlama ve sunma', 'Araştırma yapar; bilgileri düzenler; slayt destekli sunum hazırlar ve sunar.', 'Türkçe', 'ortaokul'),
  ('T.7.6.3', 'Türkçe', 7, 3, 'Sağlık', 'Fiil çekimi: gelecek zaman ve geçmiş zaman', 'Gelecek ve geçmiş zaman çekimlerini doğru kullanır.', 'Türkçe', 'ortaokul'),
  ('T.7.1.5', 'Türkçe', 7, 4, 'Aile ve Toplum', 'Farklı bakış açılarını belirleme', 'Metindeki yazar ve karakter bakış açılarını belirler; karşılaştırır.', 'Türkçe', 'ortaokul'),
  ('T.7.3.2', 'Türkçe', 7, 4, 'Aile ve Toplum', 'Mektup ve e-posta yazma', 'Resmi ve yarı resmi mektup yazar; e-posta yazım kurallarını uygular.', 'Türkçe', 'ortaokul'),
  ('T.7.6.4', 'Türkçe', 7, 4, 'Aile ve Toplum', 'Cümle türleri: basit, birleşik ve sıralı cümle', 'Cümle türlerini belirler; yazılarında çeşitli cümle yapıları kullanır.', 'Türkçe', 'ortaokul'),
  ('T.7.1.6', 'Türkçe', 7, 5, 'Güzel Sanatlar', 'Hikâye ve roman analizi', 'Hikâye veya roman incelemesi yapar; unsurlarını analiz eder.', 'Türkçe', 'ortaokul'),
  ('T.7.3.3', 'Türkçe', 7, 5, 'Güzel Sanatlar', 'Hikâye yazma', 'Kurguladığı olayı anlatı planına göre yazar; diyalog kullanır.', 'Türkçe', 'ortaokul'),
  ('T.7.6.5', 'Türkçe', 7, 5, 'Güzel Sanatlar', 'Cümle ögelerinin derinleştirilmesi', 'Yer ve zaman tümleçlerini, dolaylı tümleci belirler; cümleyi çözümler.', 'Türkçe', 'ortaokul'),
  ('T.7.1.7', 'Türkçe', 7, 6, 'Doğa ve Çevre', 'Eleştirel okuma: kanıt değerlendirme', 'Metindeki kanıt ve gerekçelerin geçerliliğini sorgular.', 'Türkçe', 'ortaokul'),
  ('T.7.5.1', 'Türkçe', 7, 6, 'Doğa ve Çevre', 'Haber ve belgesel dinleme/izleme', 'Haber ve belgeselde sunulan bilgileri değerlendirir; not alır.', 'Türkçe', 'ortaokul'),
  ('T.7.6.6', 'Türkçe', 7, 6, 'Doğa ve Çevre', 'Fiilimsiler: isim-fiil', 'İsim-fiil yapılarını tanır; cümle içindeki görevlerini belirler.', 'Türkçe', 'ortaokul'),
  ('T.7.1.8', 'Türkçe', 7, 7, 'Bilim ve Teknoloji', 'Bilimsel rapor okuma', 'Bilimsel rapor ve makale yapısını tanır; içeriği değerlendirir.', 'Türkçe', 'ortaokul'),
  ('T.7.3.4', 'Türkçe', 7, 7, 'Bilim ve Teknoloji', 'Makale ve rapor yazma', 'Kısa bir araştırma raporu yazar; kaynak gösterir.', 'Türkçe', 'ortaokul'),
  ('T.7.6.7', 'Türkçe', 7, 7, 'Bilim ve Teknoloji', 'Fiilimsiler: sıfat-fiil', 'Sıfat-fiil yapılarını tanır; cümle içindeki görevlerini belirler.', 'Türkçe', 'ortaokul'),
  ('T.7.1.9', 'Türkçe', 7, 8, 'Hak ve Özgürlükler', 'Hak ve özgürlük konulu metinler', 'İnsan hakları ve vatandaşlık konularındaki metinleri anlama ve yorumlama.', 'Türkçe', 'ortaokul'),
  ('T.7.4.2', 'Türkçe', 7, 8, 'Hak ve Özgürlükler', 'Münazara ve tartışma', 'Münazara kurallarına uyar; karşı argümanlara yanıt verir.', 'Türkçe', 'ortaokul'),
  ('T.7.6.8', 'Türkçe', 7, 8, 'Hak ve Özgürlükler', 'Fiilimsiler: zarf-fiil', 'Zarf-fiil yapılarını tanır; cümle içindeki görevlerini belirler.', 'Türkçe', 'ortaokul'),
  ('T.8.1.1', 'Türkçe', 8, 1, 'Milli Kültürümüz', 'Edebi metin türlerini anlama ve çözümleme', 'Şiir, hikâye, roman ve tiyatro türlerini karşılaştırır; temel özelliklerini belirler.', 'Türkçe', 'ortaokul'),
  ('T.8.1.2', 'Türkçe', 8, 1, 'Milli Kültürümüz', 'Dil kullanımını çözümleme', 'Metindeki söz sanatlarını (benzetme, kişileştirme, abartma) tanır ve yorumlar.', 'Türkçe', 'ortaokul'),
  ('T.8.6.1', 'Türkçe', 8, 1, 'Milli Kültürümüz', 'Cümle anlam özellikleri', 'Olumlu-olumsuz, soru, ünlem cümle türlerini ve anlamlarını kavrar.', 'Türkçe', 'ortaokul'),
  ('T.8.1.3', 'Türkçe', 8, 2, 'Atatürk ve Türkiye Cumhuriyeti', 'Cumhuriyet tarihi ve Atatürk konulu metinler', 'Tarihsel bağlamda metni yorumlar; bilgiler arasında ilişki kurar.', 'Türkçe', 'ortaokul'),
  ('T.8.3.1', 'Türkçe', 8, 2, 'Atatürk ve Türkiye Cumhuriyeti', 'Tarihi konu metin yazma', 'Tarihsel konuda araştırma yaparak bilgilendirici metin yazar.', 'Türkçe', 'ortaokul'),
  ('T.8.6.2', 'Türkçe', 8, 2, 'Atatürk ve Türkiye Cumhuriyeti', 'Cümle yapısı: basit ve birleşik', 'Basit, bağlı, sıralı ve girişik birleşik cümleleri tanır ve kullanır.', 'Türkçe', 'ortaokul'),
  ('T.8.1.4', 'Türkçe', 8, 3, 'Sağlık ve Çevre', 'Karmaşık bilgi metinlerini anlama', 'Soyut kavramlar içeren metinleri anlar; teknik terimleri bağlamdan çıkarır.', 'Türkçe', 'ortaokul'),
  ('T.8.4.1', 'Türkçe', 8, 3, 'Sağlık ve Çevre', 'LGS sözlü beceriler', 'Hazırlıklı ve hazırlıksız konuşma yapar; dinleyiciye uygun dil kullanır.', 'Türkçe', 'ortaokul'),
  ('T.8.6.3', 'Türkçe', 8, 3, 'Sağlık ve Çevre', 'Paragraf yapısı ve yazım kuralları', 'Paragraf açma cümlesi, gelişme ve kapanış cümlesini belirler; noktalama kurallarını uygular.', 'Türkçe', 'ortaokul'),
  ('T.8.1.5', 'Türkçe', 8, 4, 'Birey ve Toplum', 'Makale ve köşe yazısı anlama', 'Makale ve köşe yazısının yapısını ve amacını belirler; görüşü değerlendirir.', 'Türkçe', 'ortaokul'),
  ('T.8.3.2', 'Türkçe', 8, 4, 'Birey ve Toplum', 'Eleştirel ve kanıt tabanlı yazma', 'Kanıtlarla desteklenen eleştirel bir paragraf veya kısa metin yazar.', 'Türkçe', 'ortaokul'),
  ('T.8.6.4', 'Türkçe', 8, 4, 'Birey ve Toplum', 'Söz sanatları', 'Benzetme, istiare, kişileştirme, abartma söz sanatlarını tanır ve kullanır.', 'Türkçe', 'ortaokul'),
  ('T.8.1.6', 'Türkçe', 8, 5, 'Bilim ve Teknoloji', 'Dijital metin okuma ve değerlendirme', 'İnternette okuduğu bilgilerin güvenilirliğini sorgular; kaynakları karşılaştırır.', 'Türkçe', 'ortaokul'),
  ('T.8.5.1', 'Türkçe', 8, 5, 'Bilim ve Teknoloji', 'Dinleme: değerlendirici dinleme', 'Dinlediğini eleştirel bir gözle değerlendirir; güçlü ve zayıf yönlerini belirler.', 'Türkçe', 'ortaokul'),
  ('T.8.6.5', 'Türkçe', 8, 5, 'Bilim ve Teknoloji', 'Anlatım bozuklukları', 'Anlatım bozukluğu türlerini tanır; hatalı cümleleri düzeltir.', 'Türkçe', 'ortaokul'),
  ('T.8.1.7', 'Türkçe', 8, 6, 'Sanat ve Kültür', 'Roman okuma ve inceleme', 'Roman unsurlarını derinlemesine inceler; yazarın üslubunu değerlendirir.', 'Türkçe', 'ortaokul'),
  ('T.8.3.3', 'Türkçe', 8, 6, 'Sanat ve Kültür', 'Deneme ve eleştiri yazma', 'Bir sanat eseri veya kitap hakkında kısa eleştiri yazar.', 'Türkçe', 'ortaokul'),
  ('T.8.6.6', 'Türkçe', 8, 6, 'Sanat ve Kültür', 'LGS Türkçe dil bilgisi tekrarı', 'LGS kapsamındaki dil bilgisi konularını tekrar eder.', 'Türkçe', 'ortaokul')
) AS v(kod, brans, sinif, unite_no, unite_ad, ad, aciklama, ders, okul_tipi)
JOIN branslar b ON b.ad = v.brans
ON CONFLICT (kod) DO NOTHING;
