-- Yaver V1 — Seed: TDE (beceri-bazlı) + T.C. İnkılap Tarihi → Tarih + İnsan Hakları → Sınıf Öğretmenliği
-- 393 kazanım
-- Oluşturulma: 2026-05-03T08:33:43.166Z

INSERT INTO kazanimlar (kod, brans_id, sinif, unite_no, unite_ad, ad, aciklama)
SELECT
  v.kod, b.id, v.sinif::integer, v.unite_no::integer, v.unite_ad, v.ad, v.aciklama
FROM (VALUES
  ('TDE.9.A.1.1', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şiirde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.9.A.1.2', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şiirde tema ve konuyu belirler.', ''),
  ('TDE.9.A.1.3', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şiirde anlam ilişkilerini belirler.', ''),
  ('TDE.9.A.1.4', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şiirde ses ve ritim unsurlarını belirler.', ''),
  ('TDE.9.A.1.5', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şiirde yapı özelliklerini belirler.', ''),
  ('TDE.9.A.1.6', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şiirin türünü ve dönemini belirler.', ''),
  ('TDE.9.A.1.7', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şiirde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.9.A.1.9', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şiiri anlamlandırır ve yorumlar.', ''),
  ('TDE.9.A.1.10', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şair ile şiir arasındaki ilişkiyi değerlendirir.', ''),
  ('TDE.9.A.1.12', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.9.A.1.13', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Şiiri farklı metinlerle karşılaştırır.', ''),
  ('TDE.9.A.2.1', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.9.A.2.2', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde tema ve konuyu belirler.', ''),
  ('TDE.9.A.2.3', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde anlam ilişkilerini belirler.', ''),
  ('TDE.9.A.2.4', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde metin yapısını ve türünü belirler.', ''),
  ('TDE.9.A.2.5', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde olay örgüsünü belirler.', ''),
  ('TDE.9.A.2.6', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde şahıs kadrosunu belirler.', ''),
  ('TDE.9.A.2.7', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde zaman ve mekânı belirler.', ''),
  ('TDE.9.A.2.8', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.9.A.2.9', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde anlatım tekniklerini ve işlevlerini belirler.', ''),
  ('TDE.9.A.2.10', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metni anlamlandırır ve yorumlar.', ''),
  ('TDE.9.A.2.11', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metinde anlatıcı ve bakış açısını belirler.', ''),
  ('TDE.9.A.2.13', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Öyküleyici metni dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.9.A.2.14', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Yazar ile metin arasındaki ilişkiyi değerlendirir.', ''),
  ('TDE.9.A.2.16', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.9.A.3.1', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metninde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.9.A.3.2', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metninde tema ve konuyu belirler.', ''),
  ('TDE.9.A.3.3', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metninde anlam ilişkilerini belirler.', ''),
  ('TDE.9.A.3.4', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metninin türünü ve dönemini belirler.', ''),
  ('TDE.9.A.3.5', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metninde yapı ve biçim özelliklerini belirler.', ''),
  ('TDE.9.A.3.6', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metninde olay örgüsünü belirler.', ''),
  ('TDE.9.A.3.7', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metninde çatışmayı belirler.', ''),
  ('TDE.9.A.3.8', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metninde şahıs kadrosunu belirler.', ''),
  ('TDE.9.A.3.9', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metninde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.9.A.3.11', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metnini anlamlandırır ve yorumlar.', ''),
  ('TDE.9.A.3.12', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Tiyatro metnini dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.9.A.3.14', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.9.A.4.1', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metinde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.9.A.4.2', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metinde tema ve konuyu belirler.', ''),
  ('TDE.9.A.4.3', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metinde anlam ilişkilerini belirler.', ''),
  ('TDE.9.A.4.4', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metinde metnin türünü ve dönemini belirler.', ''),
  ('TDE.9.A.4.5', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metinde yapı ve biçim özelliklerini belirler.', ''),
  ('TDE.9.A.4.6', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metinde düşünceyi geliştirme yollarını belirler.', ''),
  ('TDE.9.A.4.7', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metinde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.9.A.4.8', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metinde yazarın amacını, bakış açısını ve tutumunu belirler.', ''),
  ('TDE.9.A.4.9', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metni anlamlandırır ve yorumlar.', ''),
  ('TDE.9.A.4.10', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metinde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.9.A.4.11', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metni dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.9.A.4.12', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metni dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.9.A.4.13', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metni farklı metinlerle karşılaştırır.', ''),
  ('TDE.9.A.4.14', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.9.A.4.15', 'Türk Dili ve Edebiyatı', 9, 1, 'Okuma', 'Bilgilendirici metni eleştirel bir bakış açısıyla değerlendirir.', ''),
  ('TDE.9.B.1', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Yazma amacını belirleyerek planlama yapar.', ''),
  ('TDE.9.B.2', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Yazma türünü, yöntemini ve tekniğini belirler.', ''),
  ('TDE.9.B.3', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Yazma sürecini uygular.', ''),
  ('TDE.9.B.4', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Yazılı anlatımda Türkçenin kurallarına uyar.', ''),
  ('TDE.9.B.5', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Yazılı anlatımda kelime hazinesinden yararlanır.', ''),
  ('TDE.9.B.6', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Duygu, düşünce ve hayallerini yazıya aktarır.', ''),
  ('TDE.9.B.7', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Yazısında metin türünün ve yapısının özelliklerine uyar.', ''),
  ('TDE.9.B.8', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Yazılarında görsel unsurlardan yararlanır.', ''),
  ('TDE.9.B.9', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Yazılarında ulusal, manevi ve evrensel değerlere yer verir.', ''),
  ('TDE.9.B.10', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Yazılarında bilgi kaynaklarından yararlanır.', ''),
  ('TDE.9.B.11', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Kendi yazısını ve başkalarının yazısını değerlendirir.', ''),
  ('TDE.9.B.12', 'Türk Dili ve Edebiyatı', 9, 2, 'Yazma', 'Dijital ortamda yazma becerilerini geliştirir.', ''),
  ('TDE.9.C.1.1', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında standart Türkçeyi kullanır.', ''),
  ('TDE.9.C.1.2', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında beden dilini etkili kullanır.', ''),
  ('TDE.9.C.1.3', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında uygun kelime ve ifadeleri seçer.', ''),
  ('TDE.9.C.1.4', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında konuya odaklanır.', ''),
  ('TDE.9.C.1.5', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında sözlü anlatım kurallarına uyar.', ''),
  ('TDE.9.C.1.6', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında duygu, düşünce ve hayallerini açıklar.', ''),
  ('TDE.9.C.1.7', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında bilgi kaynaklarından yararlanır.', ''),
  ('TDE.9.C.1.8', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında alanıyla ilgili terimleri yerinde kullanır.', ''),
  ('TDE.9.C.1.9', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında görsel ve işitsel materyallerden yararlanır.', ''),
  ('TDE.9.C.1.10', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarında ulusal, manevi ve evrensel değerlere yer verir.', ''),
  ('TDE.9.C.1.11', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Anlık konuşmalar yapar.', ''),
  ('TDE.9.C.1.12', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Hazırlıklı konuşmalar yapar.', ''),
  ('TDE.9.C.1.13', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Akademik konuşmalar yapar.', ''),
  ('TDE.9.C.1.14', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Farklı türlerde sözlü anlatım yapar.', ''),
  ('TDE.9.C.1.15', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Görsel unsurları sözlü anlatıma taşır.', ''),
  ('TDE.9.C.1.16', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Topluluk önünde sunum yapar.', ''),
  ('TDE.9.C.1.17', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Konuşmalarını değerlendirir.', ''),
  ('TDE.9.C.2.1', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Dinleme kurallarına uyar.', ''),
  ('TDE.9.C.2.2', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Dinlediğini anlar.', ''),
  ('TDE.9.C.2.3', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Dinlediğinin konusunu, ana fikrini ve yardımcı fikirlerini belirler.', ''),
  ('TDE.9.C.2.4', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Dinlediğindeki dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.9.C.2.5', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Dinlediğini özetler ve aktarır.', ''),
  ('TDE.9.C.2.6', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Dinlediğini yorumlar ve değerlendirir.', ''),
  ('TDE.9.C.2.7', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Eleştirel dinleme yapar.', ''),
  ('TDE.9.C.2.8', 'Türk Dili ve Edebiyatı', 9, 3, 'Sözlü İletişim', 'Dinleme yollarını ve stratejilerini uygular.', ''),
  ('TDE.10.A.1.1', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiirde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.10.A.1.2', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiirde tema ve konuyu belirler.', ''),
  ('TDE.10.A.1.3', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiirde anlam ilişkilerini belirler.', ''),
  ('TDE.10.A.1.4', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiirde ses ve ritim unsurlarını belirler.', ''),
  ('TDE.10.A.1.5', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiirde yapı özelliklerini belirler.', ''),
  ('TDE.10.A.1.6', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiirin türünü ve dönemini belirler.', ''),
  ('TDE.10.A.1.7', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiirde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.10.A.1.8', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiirde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.10.A.1.9', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiiri anlamlandırır ve yorumlar.', ''),
  ('TDE.10.A.1.10', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şair ile şiir arasındaki ilişkiyi değerlendirir.', ''),
  ('TDE.10.A.1.11', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiiri dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.10.A.1.12', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.10.A.1.13', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Şiiri farklı metinlerle karşılaştırır.', ''),
  ('TDE.10.A.2.1', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.10.A.2.2', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde tema ve konuyu belirler.', ''),
  ('TDE.10.A.2.3', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde anlam ilişkilerini belirler.', ''),
  ('TDE.10.A.2.4', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde metin yapısını ve türünü belirler.', ''),
  ('TDE.10.A.2.5', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde olay örgüsünü belirler.', ''),
  ('TDE.10.A.2.6', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde şahıs kadrosunu belirler.', ''),
  ('TDE.10.A.2.7', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde zaman ve mekânı belirler.', ''),
  ('TDE.10.A.2.8', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.10.A.2.9', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde anlatım tekniklerini ve işlevlerini belirler.', ''),
  ('TDE.10.A.2.10', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metni anlamlandırır ve yorumlar.', ''),
  ('TDE.10.A.2.11', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde anlatıcı ve bakış açısını belirler.', ''),
  ('TDE.10.A.2.12', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metinde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.10.A.2.13', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metni dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.10.A.2.14', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Yazar ile metin arasındaki ilişkiyi değerlendirir.', ''),
  ('TDE.10.A.2.15', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Öyküleyici metni dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.10.A.2.16', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.10.A.3.1', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.10.A.3.2', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninde tema ve konuyu belirler.', ''),
  ('TDE.10.A.3.3', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninde anlam ilişkilerini belirler.', ''),
  ('TDE.10.A.3.4', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninin türünü ve dönemini belirler.', ''),
  ('TDE.10.A.3.5', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninde yapı ve biçim özelliklerini belirler.', ''),
  ('TDE.10.A.3.6', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninde olay örgüsünü belirler.', ''),
  ('TDE.10.A.3.7', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninde çatışmayı belirler.', ''),
  ('TDE.10.A.3.8', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninde şahıs kadrosunu belirler.', ''),
  ('TDE.10.A.3.9', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.10.A.3.10', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metninde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.10.A.3.11', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metnini anlamlandırır ve yorumlar.', ''),
  ('TDE.10.A.3.12', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metnini dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.10.A.3.13', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Tiyatro metnini dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.10.A.3.14', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.10.A.4.1', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metinde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.10.A.4.2', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metinde tema ve konuyu belirler.', ''),
  ('TDE.10.A.4.3', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metinde anlam ilişkilerini belirler.', ''),
  ('TDE.10.A.4.4', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metinde metnin türünü ve dönemini belirler.', ''),
  ('TDE.10.A.4.5', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metinde yapı ve biçim özelliklerini belirler.', ''),
  ('TDE.10.A.4.6', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metinde düşünceyi geliştirme yollarını belirler.', ''),
  ('TDE.10.A.4.7', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metinde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.10.A.4.8', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metinde yazarın amacını, bakış açısını ve tutumunu belirler.', ''),
  ('TDE.10.A.4.9', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metni anlamlandırır ve yorumlar.', ''),
  ('TDE.10.A.4.10', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metinde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.10.A.4.11', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metni dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.10.A.4.12', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metni dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.10.A.4.13', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metni farklı metinlerle karşılaştırır.', ''),
  ('TDE.10.A.4.14', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.10.A.4.15', 'Türk Dili ve Edebiyatı', 10, 1, 'Okuma', 'Bilgilendirici metni eleştirel bir bakış açısıyla değerlendirir.', ''),
  ('TDE.10.B.1', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Yazma amacını belirleyerek planlama yapar.', ''),
  ('TDE.10.B.2', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Yazma türünü, yöntemini ve tekniğini belirler.', ''),
  ('TDE.10.B.3', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Yazma sürecini uygular.', ''),
  ('TDE.10.B.4', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Yazılı anlatımda Türkçenin kurallarına uyar.', ''),
  ('TDE.10.B.5', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Yazılı anlatımda kelime hazinesinden yararlanır.', ''),
  ('TDE.10.B.6', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Duygu, düşünce ve hayallerini yazıya aktarır.', ''),
  ('TDE.10.B.7', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Yazısında metin türünün ve yapısının özelliklerine uyar.', ''),
  ('TDE.10.B.8', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Yazılarında görsel unsurlardan yararlanır.', ''),
  ('TDE.10.B.9', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Yazılarında ulusal, manevi ve evrensel değerlere yer verir.', ''),
  ('TDE.10.B.10', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Yazılarında bilgi kaynaklarından yararlanır.', ''),
  ('TDE.10.B.11', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Kendi yazısını ve başkalarının yazısını değerlendirir.', ''),
  ('TDE.10.B.12', 'Türk Dili ve Edebiyatı', 10, 2, 'Yazma', 'Dijital ortamda yazma becerilerini geliştirir.', ''),
  ('TDE.10.C.1.2', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarında beden dilini etkili kullanır.', ''),
  ('TDE.10.C.1.3', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarında uygun kelime ve ifadeleri seçer.', ''),
  ('TDE.10.C.1.4', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarında konuya odaklanır.', ''),
  ('TDE.10.C.1.5', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarında sözlü anlatım kurallarına uyar.', ''),
  ('TDE.10.C.1.6', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarında duygu, düşünce ve hayallerini açıklar.', ''),
  ('TDE.10.C.1.7', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarında bilgi kaynaklarından yararlanır.', ''),
  ('TDE.10.C.1.8', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarında alanıyla ilgili terimleri yerinde kullanır.', ''),
  ('TDE.10.C.1.9', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarında görsel ve işitsel materyallerden yararlanır.', ''),
  ('TDE.10.C.1.10', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarında ulusal, manevi ve evrensel değerlere yer verir.', ''),
  ('TDE.10.C.1.11', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Anlık konuşmalar yapar.', ''),
  ('TDE.10.C.1.12', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Hazırlıklı konuşmalar yapar.', ''),
  ('TDE.10.C.1.13', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Akademik konuşmalar yapar.', ''),
  ('TDE.10.C.1.14', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Farklı türlerde sözlü anlatım yapar.', ''),
  ('TDE.10.C.1.15', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Görsel unsurları sözlü anlatıma taşır.', ''),
  ('TDE.10.C.1.16', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Topluluk önünde sunum yapar.', ''),
  ('TDE.10.C.1.17', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Konuşmalarını değerlendirir.', ''),
  ('TDE.10.C.2.1', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Dinleme kurallarına uyar.', ''),
  ('TDE.10.C.2.2', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Dinlediğini anlar.', ''),
  ('TDE.10.C.2.3', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Dinlediğinin konusunu, ana fikrini ve yardımcı fikirlerini belirler.', ''),
  ('TDE.10.C.2.4', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Dinlediğindeki dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.10.C.2.5', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Dinlediğini özetler ve aktarır.', ''),
  ('TDE.10.C.2.6', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Dinlediğini yorumlar ve değerlendirir.', ''),
  ('TDE.10.C.2.7', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Eleştirel dinleme yapar.', ''),
  ('TDE.10.C.2.8', 'Türk Dili ve Edebiyatı', 10, 3, 'Sözlü İletişim', 'Dinleme yollarını ve stratejilerini uygular.', ''),
  ('TDE.11.A.1.1', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiirde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.11.A.1.2', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiirde tema ve konuyu belirler.', ''),
  ('TDE.11.A.1.3', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiirde anlam ilişkilerini belirler.', ''),
  ('TDE.11.A.1.4', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiirde ses ve ritim unsurlarını belirler.', ''),
  ('TDE.11.A.1.5', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiirde yapı özelliklerini belirler.', ''),
  ('TDE.11.A.1.6', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiirin türünü ve dönemini belirler.', ''),
  ('TDE.11.A.1.7', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiirde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.11.A.1.8', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiirde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.11.A.1.9', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiiri anlamlandırır ve yorumlar.', ''),
  ('TDE.11.A.1.10', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şair ile şiir arasındaki ilişkiyi değerlendirir.', ''),
  ('TDE.11.A.1.11', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiiri dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.11.A.1.12', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.11.A.1.13', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Şiiri farklı metinlerle karşılaştırır.', ''),
  ('TDE.11.A.2.1', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.11.A.2.2', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde tema ve konuyu belirler.', ''),
  ('TDE.11.A.2.3', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde anlam ilişkilerini belirler.', ''),
  ('TDE.11.A.2.4', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde metin yapısını ve türünü belirler.', ''),
  ('TDE.11.A.2.5', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde olay örgüsünü belirler.', ''),
  ('TDE.11.A.2.6', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde şahıs kadrosunu belirler.', ''),
  ('TDE.11.A.2.7', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde zaman ve mekânı belirler.', ''),
  ('TDE.11.A.2.8', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.11.A.2.9', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde anlatım tekniklerini ve işlevlerini belirler.', ''),
  ('TDE.11.A.2.10', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metni anlamlandırır ve yorumlar.', ''),
  ('TDE.11.A.2.11', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde anlatıcı ve bakış açısını belirler.', ''),
  ('TDE.11.A.2.12', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metinde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.11.A.2.13', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metni dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.11.A.2.14', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Yazar ile metin arasındaki ilişkiyi değerlendirir.', ''),
  ('TDE.11.A.2.15', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Öyküleyici metni dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.11.A.2.16', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.11.A.3.1', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.11.A.3.2', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninde tema ve konuyu belirler.', ''),
  ('TDE.11.A.3.3', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninde anlam ilişkilerini belirler.', ''),
  ('TDE.11.A.3.4', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninin türünü ve dönemini belirler.', ''),
  ('TDE.11.A.3.5', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninde yapı ve biçim özelliklerini belirler.', ''),
  ('TDE.11.A.3.6', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninde olay örgüsünü belirler.', ''),
  ('TDE.11.A.3.7', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninde çatışmayı belirler.', ''),
  ('TDE.11.A.3.8', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninde şahıs kadrosunu belirler.', ''),
  ('TDE.11.A.3.9', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.11.A.3.10', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metninde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.11.A.3.11', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metnini anlamlandırır ve yorumlar.', ''),
  ('TDE.11.A.3.12', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metnini dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.11.A.3.13', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Tiyatro metnini dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.11.A.3.14', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.11.A.4.1', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metinde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.11.A.4.2', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metinde tema ve konuyu belirler.', ''),
  ('TDE.11.A.4.3', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metinde anlam ilişkilerini belirler.', ''),
  ('TDE.11.A.4.4', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metinde metnin türünü ve dönemini belirler.', ''),
  ('TDE.11.A.4.5', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metinde yapı ve biçim özelliklerini belirler.', ''),
  ('TDE.11.A.4.6', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metinde düşünceyi geliştirme yollarını belirler.', ''),
  ('TDE.11.A.4.7', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metinde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.11.A.4.8', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metinde yazarın amacını, bakış açısını ve tutumunu belirler.', ''),
  ('TDE.11.A.4.9', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metni anlamlandırır ve yorumlar.', ''),
  ('TDE.11.A.4.10', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metinde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.11.A.4.11', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metni dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.11.A.4.12', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metni dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.11.A.4.13', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metni farklı metinlerle karşılaştırır.', ''),
  ('TDE.11.A.4.14', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.11.A.4.15', 'Türk Dili ve Edebiyatı', 11, 1, 'Okuma', 'Bilgilendirici metni eleştirel bir bakış açısıyla değerlendirir.', ''),
  ('TDE.11.B.1', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Yazma amacını belirleyerek planlama yapar.', ''),
  ('TDE.11.B.2', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Yazma türünü, yöntemini ve tekniğini belirler.', ''),
  ('TDE.11.B.3', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Yazma sürecini uygular.', ''),
  ('TDE.11.B.4', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Yazılı anlatımda Türkçenin kurallarına uyar.', ''),
  ('TDE.11.B.5', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Yazılı anlatımda kelime hazinesinden yararlanır.', ''),
  ('TDE.11.B.6', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Duygu, düşünce ve hayallerini yazıya aktarır.', ''),
  ('TDE.11.B.7', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Yazısında metin türünün ve yapısının özelliklerine uyar.', ''),
  ('TDE.11.B.8', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Yazılarında görsel unsurlardan yararlanır.', ''),
  ('TDE.11.B.9', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Yazılarında ulusal, manevi ve evrensel değerlere yer verir.', ''),
  ('TDE.11.B.10', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Yazılarında bilgi kaynaklarından yararlanır.', ''),
  ('TDE.11.B.11', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Kendi yazısını ve başkalarının yazısını değerlendirir.', ''),
  ('TDE.11.B.12', 'Türk Dili ve Edebiyatı', 11, 2, 'Yazma', 'Dijital ortamda yazma becerilerini geliştirir.', ''),
  ('TDE.11.C.1.2', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarında beden dilini etkili kullanır.', ''),
  ('TDE.11.C.1.3', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarında uygun kelime ve ifadeleri seçer.', ''),
  ('TDE.11.C.1.4', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarında konuya odaklanır.', ''),
  ('TDE.11.C.1.5', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarında sözlü anlatım kurallarına uyar.', ''),
  ('TDE.11.C.1.6', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarında duygu, düşünce ve hayallerini açıklar.', ''),
  ('TDE.11.C.1.7', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarında bilgi kaynaklarından yararlanır.', ''),
  ('TDE.11.C.1.8', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarında alanıyla ilgili terimleri yerinde kullanır.', ''),
  ('TDE.11.C.1.9', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarında görsel ve işitsel materyallerden yararlanır.', ''),
  ('TDE.11.C.1.10', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarında ulusal, manevi ve evrensel değerlere yer verir.', ''),
  ('TDE.11.C.1.11', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Anlık konuşmalar yapar.', ''),
  ('TDE.11.C.1.12', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Hazırlıklı konuşmalar yapar.', ''),
  ('TDE.11.C.1.13', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Akademik konuşmalar yapar.', ''),
  ('TDE.11.C.1.14', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Farklı türlerde sözlü anlatım yapar.', ''),
  ('TDE.11.C.1.15', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Görsel unsurları sözlü anlatıma taşır.', ''),
  ('TDE.11.C.1.16', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Topluluk önünde sunum yapar.', ''),
  ('TDE.11.C.1.17', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Konuşmalarını değerlendirir.', ''),
  ('TDE.11.C.2.1', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Dinleme kurallarına uyar.', ''),
  ('TDE.11.C.2.2', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Dinlediğini anlar.', ''),
  ('TDE.11.C.2.3', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Dinlediğinin konusunu, ana fikrini ve yardımcı fikirlerini belirler.', ''),
  ('TDE.11.C.2.4', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Dinlediğindeki dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.11.C.2.5', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Dinlediğini özetler ve aktarır.', ''),
  ('TDE.11.C.2.6', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Dinlediğini yorumlar ve değerlendirir.', ''),
  ('TDE.11.C.2.7', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Eleştirel dinleme yapar.', ''),
  ('TDE.11.C.2.8', 'Türk Dili ve Edebiyatı', 11, 3, 'Sözlü İletişim', 'Dinleme yollarını ve stratejilerini uygular.', ''),
  ('TDE.12.A.1.1', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiirde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.12.A.1.2', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiirde tema ve konuyu belirler.', ''),
  ('TDE.12.A.1.3', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiirde anlam ilişkilerini belirler.', ''),
  ('TDE.12.A.1.4', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiirde ses ve ritim unsurlarını belirler.', ''),
  ('TDE.12.A.1.5', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiirde yapı özelliklerini belirler.', ''),
  ('TDE.12.A.1.6', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiirin türünü ve dönemini belirler.', ''),
  ('TDE.12.A.1.7', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiirde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.12.A.1.8', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiirde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.12.A.1.9', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiiri anlamlandırır ve yorumlar.', ''),
  ('TDE.12.A.1.10', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şair ile şiir arasındaki ilişkiyi değerlendirir.', ''),
  ('TDE.12.A.1.11', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiiri dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.12.A.1.12', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.12.A.1.13', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Şiiri farklı metinlerle karşılaştırır.', ''),
  ('TDE.12.A.2.1', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.12.A.2.2', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde tema ve konuyu belirler.', ''),
  ('TDE.12.A.2.3', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde anlam ilişkilerini belirler.', ''),
  ('TDE.12.A.2.4', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde metin yapısını ve türünü belirler.', ''),
  ('TDE.12.A.2.5', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde olay örgüsünü belirler.', ''),
  ('TDE.12.A.2.6', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde şahıs kadrosunu belirler.', ''),
  ('TDE.12.A.2.7', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde zaman ve mekânı belirler.', ''),
  ('TDE.12.A.2.8', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.12.A.2.9', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde anlatım tekniklerini ve işlevlerini belirler.', ''),
  ('TDE.12.A.2.10', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metni anlamlandırır ve yorumlar.', ''),
  ('TDE.12.A.2.11', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde anlatıcı ve bakış açısını belirler.', ''),
  ('TDE.12.A.2.12', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metinde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.12.A.2.13', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metni dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.12.A.2.14', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Yazar ile metin arasındaki ilişkiyi değerlendirir.', ''),
  ('TDE.12.A.2.15', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Öyküleyici metni dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.12.A.2.16', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.12.A.3.1', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.12.A.3.2', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninde tema ve konuyu belirler.', ''),
  ('TDE.12.A.3.3', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninde anlam ilişkilerini belirler.', ''),
  ('TDE.12.A.3.4', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninin türünü ve dönemini belirler.', ''),
  ('TDE.12.A.3.5', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninde yapı ve biçim özelliklerini belirler.', ''),
  ('TDE.12.A.3.6', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninde olay örgüsünü belirler.', ''),
  ('TDE.12.A.3.7', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninde çatışmayı belirler.', ''),
  ('TDE.12.A.3.8', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninde şahıs kadrosunu belirler.', ''),
  ('TDE.12.A.3.9', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.12.A.3.10', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metninde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.12.A.3.11', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metnini anlamlandırır ve yorumlar.', ''),
  ('TDE.12.A.3.12', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metnini dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.12.A.3.13', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Tiyatro metnini dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.12.A.3.14', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.12.A.4.1', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metinde sözcük ve söz öbeklerinin anlam özelliklerini belirler.', ''),
  ('TDE.12.A.4.2', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metinde tema ve konuyu belirler.', ''),
  ('TDE.12.A.4.3', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metinde anlam ilişkilerini belirler.', ''),
  ('TDE.12.A.4.4', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metinde metnin türünü ve dönemini belirler.', ''),
  ('TDE.12.A.4.5', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metinde yapı ve biçim özelliklerini belirler.', ''),
  ('TDE.12.A.4.6', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metinde düşünceyi geliştirme yollarını belirler.', ''),
  ('TDE.12.A.4.7', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metinde dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.12.A.4.8', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metinde yazarın amacını, bakış açısını ve tutumunu belirler.', ''),
  ('TDE.12.A.4.9', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metni anlamlandırır ve yorumlar.', ''),
  ('TDE.12.A.4.10', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metinde ulusal, manevi ve evrensel değerleri belirler.', ''),
  ('TDE.12.A.4.11', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metni dönemin özellikleriyle ilişkilendirir.', ''),
  ('TDE.12.A.4.12', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metni dönemin sosyal, siyasi, tarihi ve kültürel özellikleriyle ilişkilendirir.', ''),
  ('TDE.12.A.4.13', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metni farklı metinlerle karşılaştırır.', ''),
  ('TDE.12.A.4.14', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Metinden hareketle dil bilgisi çalışmaları yapar.', ''),
  ('TDE.12.A.4.15', 'Türk Dili ve Edebiyatı', 12, 1, 'Okuma', 'Bilgilendirici metni eleştirel bir bakış açısıyla değerlendirir.', ''),
  ('TDE.12.B.1', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Yazma amacını belirleyerek planlama yapar.', ''),
  ('TDE.12.B.2', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Yazma türünü, yöntemini ve tekniğini belirler.', ''),
  ('TDE.12.B.3', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Yazma sürecini uygular.', ''),
  ('TDE.12.B.4', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Yazılı anlatımda Türkçenin kurallarına uyar.', ''),
  ('TDE.12.B.5', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Yazılı anlatımda kelime hazinesinden yararlanır.', ''),
  ('TDE.12.B.6', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Duygu, düşünce ve hayallerini yazıya aktarır.', ''),
  ('TDE.12.B.7', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Yazısında metin türünün ve yapısının özelliklerine uyar.', ''),
  ('TDE.12.B.8', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Yazılarında görsel unsurlardan yararlanır.', ''),
  ('TDE.12.B.9', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Yazılarında ulusal, manevi ve evrensel değerlere yer verir.', ''),
  ('TDE.12.B.10', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Yazılarında bilgi kaynaklarından yararlanır.', ''),
  ('TDE.12.B.11', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Kendi yazısını ve başkalarının yazısını değerlendirir.', ''),
  ('TDE.12.B.12', 'Türk Dili ve Edebiyatı', 12, 2, 'Yazma', 'Dijital ortamda yazma becerilerini geliştirir.', ''),
  ('TDE.12.C.1.2', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarında beden dilini etkili kullanır.', ''),
  ('TDE.12.C.1.3', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarında uygun kelime ve ifadeleri seçer.', ''),
  ('TDE.12.C.1.4', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarında konuya odaklanır.', ''),
  ('TDE.12.C.1.5', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarında sözlü anlatım kurallarına uyar.', ''),
  ('TDE.12.C.1.6', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarında duygu, düşünce ve hayallerini açıklar.', ''),
  ('TDE.12.C.1.7', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarında bilgi kaynaklarından yararlanır.', ''),
  ('TDE.12.C.1.8', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarında alanıyla ilgili terimleri yerinde kullanır.', ''),
  ('TDE.12.C.1.9', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarında görsel ve işitsel materyallerden yararlanır.', ''),
  ('TDE.12.C.1.10', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarında ulusal, manevi ve evrensel değerlere yer verir.', ''),
  ('TDE.12.C.1.11', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Anlık konuşmalar yapar.', ''),
  ('TDE.12.C.1.12', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Hazırlıklı konuşmalar yapar.', ''),
  ('TDE.12.C.1.13', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Akademik konuşmalar yapar.', ''),
  ('TDE.12.C.1.14', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Farklı türlerde sözlü anlatım yapar.', ''),
  ('TDE.12.C.1.15', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Görsel unsurları sözlü anlatıma taşır.', ''),
  ('TDE.12.C.1.16', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Topluluk önünde sunum yapar.', ''),
  ('TDE.12.C.1.17', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Konuşmalarını değerlendirir.', ''),
  ('TDE.12.C.2.1', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Dinleme kurallarına uyar.', ''),
  ('TDE.12.C.2.2', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Dinlediğini anlar.', ''),
  ('TDE.12.C.2.3', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Dinlediğinin konusunu, ana fikrini ve yardımcı fikirlerini belirler.', ''),
  ('TDE.12.C.2.4', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Dinlediğindeki dil ve anlatım özelliklerini belirler.', ''),
  ('TDE.12.C.2.5', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Dinlediğini özetler ve aktarır.', ''),
  ('TDE.12.C.2.6', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Dinlediğini yorumlar ve değerlendirir.', ''),
  ('TDE.12.C.2.7', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Eleştirel dinleme yapar.', ''),
  ('TDE.12.C.2.8', 'Türk Dili ve Edebiyatı', 12, 3, 'Sözlü İletişim', 'Dinleme yollarını ve stratejilerini uygular.', ''),
  ('İTA.12.1.1', 'Tarih', 12, 1, 'Ünite 1', 'Mustafa Kemal Paşa’nın kişilik özelliklerinin oluşmasında etkili olan unsurları çözümleyebilme', 'a) Mustafa Kemal Paşa’nın kişilik özelliklerini belirler. b) Mustafa Kemal Paşa’nın yetiştiği dönemin koşullarını, aldığı eğitimi ve askerlik deneyimini belirler.'),
  ('İTA.12.1.2', 'Tarih', 12, 1, 'Ünite 1', 'Millî Mücadele’nin hazırlık sürecinde yaşanan olaylara ilişkin bakış açısı geliştirebilme', 'a) Millî Mücadele’nin hazırlık sürecinde yaşanan olayları birinci ve ikinci elden kaynaklardan inceler. b) Millî Mücadele’nin hazırlık sürecinde yaşanan olaylarla ilgili birinci ve ikinci elden kaynakları yorumlar. c) Millî Mücadele’nin hazırlık sürecinde yaşanan olayları kaynaklara dayanarak çözümler. ç) Millî Mücadele’nin hazırlık sürecinde yaşanan olayların meydana geldiği dönemin koşullarını belirler. d) Millî Mücadele’nin hazırlık sürecinde yaşanan olayların koşullarıyla günümüzdeki yaşam k'),
  ('İTA.12.1.3', 'Tarih', 12, 1, 'Ünite 1', 'Millî Mücadele Dönemi’ndeki siyasi ve askerî gelişmelerin yeni Türk devletinin kuruluşuna etkilerini değerlendirebilme', 'a) Millî Mücadele Dönemi’ndeki siyasi ve askerî gelişmeleri sonuçları açısından karşılaştırır. b) Millî Mücadele Dönemi’ndeki siyasi ve askerî gelişmelerin yeni Türk devletinin kuruluşuna etkisine dair yargıda bulunur.'),
  ('İTA.12.1.4', 'Tarih', 12, 1, 'Ünite 1', 'Atatürk Dönemi’nde meydana gelen iç siyasi gelişmelerin yeni Türk devletinin kurumsallaşmasındaki rolüne ilişkin özgün ürün üretebilme', 'a) Atatürk Dönemi’nde meydana gelen iç siyasi gelişmeleri inceler. b) Atatürk Dönemi’nde meydana gelen iç siyasi gelişmeler ile yeni Türk devletinin kurumsallaşması arasında ilişki kurar. c) Atatürk Dönemi’nde meydana gelen iç siyasi gelişmelerin yeni Türk devletinin kurumsallaşmasındaki rolüne ilişkin özgün bir içerik oluşturur.'),
  ('İTA.12.1.5', 'Tarih', 12, 1, 'Ünite 1', 'Atatürk Dönemi’nde meydana gelen dış siyasi gelişmeleri yeni devletin öncelikleri açısından karşılaştırabilme', 'a) Atatürk Dönemi’nde meydana gelen dış siyasi gelişmeleri inceler. b) Atatürk Dönemi’nde meydana gelen dış siyasi gelişmeleri yeni devletin öncelikleri açısından benzer yönleriyle listeler. c) Atatürk Dönemi’nde meydana gelen dış siyasi gelişmeleri yeni devletin öncelikleri açısından farklı yönleriyle listeler. T.C.'),
  ('İTA.12.2.1', 'Tarih', 12, 2, 'Ünite 2', 'Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde siyasi alanda yapılan inkılapları neden ve sonuçlarıyla yorumlayabilme', 'a) Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde siyasi alanda yapılan inkılapların nedenlerini inceler. b) Atatürk Dönemi’nde siyasi alanda yapılan inkılapların etkilediği unsurları inceler. c) Siyasi alanda yapılan inkılapların devlet ve topluma etkilerini sorgular. ç) Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde siyasi alanda yapılan inkılapların nedenlerini ve sonuçlarını bağlamından kopmadan ifade eder.'),
  ('İTA.12.2.2', 'Tarih', 12, 2, 'Ünite 2', 'Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde toplumsal alan ile hukuk ve sağlıkta yapılan inkılapları günlük yaşama etkisi açısından değerlendirebilme', 'a) Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde toplumsal alan ile hukuk ve sağlıkta yapılan inkılapları günlük yaşama etkisi açısından karşılaştırır. b) Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde toplumsal alan ile hukuk ve sağlıkta yapılan inkılapların günlük yaşama etkisine ilişkin yargıda bulunur.'),
  ('İTA.12.2.3', 'Tarih', 12, 2, 'Ünite 2', 'Türk modernleşmesi çerçevesinde Atatürk Dönemi’ndeki devletçi politika anlayışının ekonomi alanında yapılan inkılaplara etkisini sorgulayabilme', 'a) Türk modernleşmesi çerçevesinde Atatürk Dönemi’ndeki devletçi politika anlayışının ekonomi alanında yapılan inkılaplara etkisi hakkında merak ettiği konuları belirler. b) İlgili konular hakkında sorular sorar (5N1K). c) Farklı kaynaklar üzerinden konuya ilişkin bilgi toplar. ç) Topladığı bilgilerin doğruluğunu değerlendirir. d) Türk modernleşmesi çerçevesinde Atatürk Dönemi’ndeki devletçi politika anlayışının ekonomi alanında yapılan inkılaplara etkisi hakkında çıkarım yapar.'),
  ('İTA.12.2.4', 'Tarih', 12, 2, 'Ünite 2', 'Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde eğitim, bilim ve kültür alanlarında yapılan inkılapları değişim ve süreklilik açısından karşılaştırabilme', 'a) Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde eğitim, bilim ve kültür alanlarında yapılan inkılapları belirler. b) Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde eğitim, bilim ve kültür alanlarında yapılan inkılaplara ilişkin benzerlikleri listeler. c) Türk modernleşmesi çerçevesinde Atatürk Dönemi’nde eğitim, bilim ve kültür alanlarında yapılan inkılaplara ilişkin farklılıkları listeler.'),
  ('İTA.12.2.5', 'Tarih', 12, 2, 'Ünite 2', 'Türk modernleşmesinin Atatürk ilkelerinin oluşumuna etkisini yorumlayabilme', 'a) Türk modernleşmesinin Atatürk ilkelerinin oluşumuna etkisini inceler. b) Türk modernleşmesinin Atatürk ilkelerinin oluşumuna etkisini bağlamından kopmadan dönüştürür. c) Türk modernleşmesinin Atatürk ilkelerinin oluşumuna etkisini ifade eder. T.C.'),
  ('İTA.12.3.2', 'Tarih', 12, 3, 'Ünite 3', 'II. Dünya Savaşı sürecinde Türkiye’nin iç ve dış siyasetinde karşılaştığı sorunların çözümüne yönelik alternatif fikirler üretebilme', 'a) II. Dünya Savaşı sürecinde Türkiye’nin iç ve dış siyasetinde karşılaştığı tarihsel bir sorunu tanımlar. b) II. Dünya Savaşı sürecinde Türkiye’nin iç ve dış siyasetinde karşılaştığı tarihsel soruna ilişkin tarafların bakış açılarını çözümler. c) II. Dünya Savaşı sürecinde Türkiye’nin iç ve dış siyasetinde karşılaştığı tarihsel sorunun çözümü için yapılan uygulamaları ve alınan kararları değerlendirir. ç) II. Dünya Savaşı sürecinde Türkiye’nin iç ve dış siyasetinde karşılaştığı tarihsel sorunun'),
  ('İTA.12.3.3', 'Tarih', 12, 3, 'Ünite 3', 'Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’nin dış politikasındaki değişim ve sürekliliği neden ve sonuçlarıyla yorumlayabilme', 'a) Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’nin dış politikasındaki değişim ve sürekliliğe neden olan unsurları inceler. b) Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’nin dış politikasındaki değişim ve sürekliliğin etkilediği unsurları inceler. c) Soğuk Savaş Dönemi’nin başlangıcından itibaren yaşanan gelişmeleri Türkiye’nin dış politikasındaki değişim ve sürekliliğe etkileri açısından sorgular. ç) Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’nin dış politikas'),
  ('İTA.12.3.4', 'Tarih', 12, 3, 'Ünite 3', 'Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’de meydana gelen siyasi gelişmelerin demokratikleşme sürecine etkilerini yorumlayabilme', 'a) Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’de meydana gelen siyasi gelişmelere ilişkin verilen kaynakları inceler. b) Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’de meydana gelen siyasi gelişmelere ilişkin kaynaklarda verilen bilgileri bağlamından kopmadan sözlü, yazılı, görsel biçimlere dönüştürür. c) Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’de meydana gelen siyasi gelişmeleri demokratikleşme sürecine etkileri açısından kendi ifadeleriyle açıklar. T.C.'),
  ('İTA.12.3.5', 'Tarih', 12, 3, 'Ünite 3', 'Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’deki sosyal ve ekonomik gelişmeleri toplumsal etkileri açısından değerlendirebilme', 'a) Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’deki sosyal ve ekonomik gelişmeleri toplumsal etkileri bakımından karşılaştırır. b) Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’deki sosyal ve ekonomik gelişmelerle ilgili yaptığı karşılaştırmalara yönelik yargıda bulunur.'),
  ('İTA.12.3.6', 'Tarih', 12, 3, 'Ünite 3', 'Soğuk Savaş Dönemi’nin başlangıcından itibaren Türkiye’de bilim, teknoloji, kültür, eğitim ve spor alanlarında yaşanan gelişmelere ilişkin oluşturduğu özgün ürünleri paylaşabilme', 'a) Türkiye’de bilim, teknoloji, kültür, eğitim ve spor alanlarında yaşanan gelişmeler hakkındaki araştırmasına dair belirlediği kaynaklardan bilgi toplar. b) Türkiye’de bilim, teknoloji, kültür, eğitim ve spor alanlarında yaşanan gelişmelere ilişkin topladığı bilgilerin araştırmasına uygunluğunu belirler. c) Türkiye’de bilim, teknoloji, kültür, eğitim ve spor alanlarında yaşanan gelişmelere ilişkin kullanacağı kaynakların sınırlılığını sorgular. ç) Türkiye’de bilim, teknoloji, kültür, eğitim ve '),
  ('İHVD.4.1.2', 'Sınıf Öğretmenliği', 4, 1, 'Ünite 1', 'Çocuk haklarıyla ilgili kanıta dayalı olarak oluşturduğu ürünü paylaşabilme', 'a) Verilen kanıtlara dayanarak çocuk haklarına ihtiyaç duyulma sebeplerini tespit eder. b) Tespitleri bağlamında kendi çocuk hakları sözleşmesini oluşturur. c) Çocuk Hakları Sözleşmesi’nin maddelerini sözlü veya görsel olarak yeniden ifade eder.'),
  ('İHVD.4.1.3', 'Sınıf Öğretmenliği', 4, 1, 'Ünite 1', 'İnsan olmanın getirdiği temel hak ve özgürlükleri yorumlayabilme', 'a) İnsan olmanın getirdiği temel hak ve özgürlükleri örnekler üzerinden inceler. b) İnsan olmanın getirdiği temel hak ve özgürlükleri bağlamdan kopmadan yazılı veya sözlü olarak ifade eder. c) İnsan olmanın getirdiği temel hak ve özgürlükleri kendi cümleleri ile ifade eder.'),
  ('İHVD.4.2.2', 'Sınıf Öğretmenliği', 4, 2, 'Ünite 2', 'Adalet ve eşitlik arasındaki ilişkiyi yorumlayabilme', 'a) Adalet ve eşitlik kavramları arasındaki ilişkiyi inceler. b) Adalet ve eşitlik kavramları arasındaki ilişkiyi bağlamdan kopmadan, sözlü veya görsel olarak ifade eder. c) Adalet ve eşitlik kavramlarını kendi hayatından örnekler vererek ifade eder.'),
  ('İHVD.4.2.3', 'Sınıf Öğretmenliği', 4, 2, 'Ünite 2', 'Fırsat eşitliğinin anlamını yorumlayabilme', 'a) Fırsat eşitliğine ilişkin durumları inceler. b) Fırsat eşitliğinin önemini sözlü, yazılı veya görsel olarak ifade eder. c) Fırsat eşitliği ile ilgili yakın çevresinden örnekler verir.'),
  ('İHVD.4.3.4', 'Sınıf Öğretmenliği', 4, 3, 'Ünite 3', 'Etkin bir vatandaş olarak toplumsal yardımlaşma faaliyetleri ile ilgili fikir üretebilme', 'a) Toplumsal yardımlaşma faaliyetlerinin önemini fark eder. b) Toplumsal yardımlaşma faaliyetlerine ilişkin örnekleri inceler. c) Toplumsal yardımlaşma faaliyetleriyle ilgili fikir üretir.'),
  ('İHVD.4.4.2', 'Sınıf Öğretmenliği', 4, 4, 'Ünite 4', 'Grup arkadaşları ile farklı fikirler hakkında müzakere edebilme', 'a) Yakın çevresinde dâhil olduğu gruplarda yer alan üyelerin kendisinden farklı düşünebileceğini fark eder. b) Yakın çevresinde dâhil olduğu gruplarda yer alan üyelerin düşüncelerindeki ortaklıkları ve farklılıkları karşılaştırır. c) Yakın çevresinde dâhil olduğu gruplarda yer alan üyelerin farklı görüş ve düşünceleri doğrultusunda ortak amaç üzerinde uzlaşmak için çözüm arar. ç) Yakın çevresinde dâhil olduğu gruplarda yer alan üyelerin farklı görüş ve düşüncelerini dikkate alarak ortak amaca gö'),
  ('İHVD.4.4.3', 'Sınıf Öğretmenliği', 4, 4, 'Ünite 4', 'Seçme ve seçilme hakkı konusunda fikir üretebilme', 'a) Seçme hakkının toplumsal yaşam için önemini fark eder. b) Seçme ve seçilme hakkıyla ilgili yakın çevresindeki deneyimleri inceler. c) Seçme ve seçilme hakkının yaşantısındaki farklı alanlara uygulanması hususunda fikir üretir.')
) AS v(kod, brans_ad, sinif, unite_no, unite_ad, ad, aciklama)
JOIN branslar b ON b.ad = v.brans_ad
ON CONFLICT (kod) DO NOTHING;
